Repository eclipse-theia/theia, pull requests merged in 2020-11, with the labels that each got.

#8645 Allow debug widgets to get updated when not visible
  packages/debug/src/browser/view/debug-session-widget.ts
Labels: debug

#8704 [Fix] Webview is covered with transparent overlay when clicking inside it
  packages/plugin-ext/src/main/browser/webview/webview.ts
Labels: bug, webviews

#8686 Add API doc for 'BackendApplicationContribution'
  packages/core/src/node/backend-application.ts
Labels: documentation

#8698 Documentation for `TreeDecorator` & `TreeDecoratorService`
  packages/core/src/browser/tree/tree-decorator.ts
Labels: core, documentation

#8720 yarn upgrade
  .travis.yml
  yarn.lock
Labels: dependencies, quality

#8688 Add API documentation for 'MessageService'
  packages/core/src/common/message-service-protocol.ts
  packages/core/src/common/message-service.ts
Labels: documentation, messaging

#8695 Improve documentation for `TaskAPI`
  packages/task/src/browser/task-contribution.ts
  packages/task/src/node/task-manager.ts
  packages/task/src/node/task-runner.ts
  packages/task/src/node/task.ts
Labels: documentation, tasks

#8715 Add API documentation for 'MenuContribution'
  packages/core/src/common/menu.ts
Labels: documentation, menus

#8710 plugin: Add support for `activeColorTheme` and `onDidChangeActiveColorTheme` API
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/main-context.ts
  packages/plugin-ext/src/main/browser/theming-main.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/theming.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
Labels: CQ Required, vscode

#8719 documentation: update 'publishing' docs
  doc/Publishing.md
Labels: documentation

#8711 deps: update 'yargs' dependency and typings
  dev-packages/application-manager/src/generator/abstract-generator.ts
  dev-packages/application-manager/src/rebuild.ts
  dev-packages/cli/package.json
  dev-packages/cli/src/theia.ts
  dev-packages/electron/package.json
  packages/core/package.json
  packages/core/src/node/backend-application.ts
  packages/core/src/node/cli.spec.ts
  packages/core/src/node/logger-cli-contribution.ts
  packages/plugin-ext-vscode/src/node/plugin-vscode-cli-contribution.ts
  packages/plugin-ext/src/hosted/node/hosted-plugin-cli-contribution.ts
  packages/plugin-ext/src/main/node/plugin-cli-contribution.ts
  packages/workspace/src/node/default-workspace-server.ts
  yarn.lock
Labels: dependencies, quality, security

#8736 ci: fix 'saveable' test-case
  examples/api-tests/src/saveable.spec.js
Labels: ci, file-watchers

#8540 Filter button in search box
  packages/core/src/browser/style/search-box.css
  packages/core/src/browser/tree/search-box.ts
  packages/core/src/browser/tree/tree-search.ts
  packages/core/src/browser/tree/tree-widget.tsx
  packages/scm/src/browser/scm-tree-widget.tsx
Labels: enhancement, tree

#8734 [Fix] WorkspaceFrontendContribution is not binded to FrontendApplication
  packages/workspace/src/browser/workspace-frontend-module.ts
Labels: bug, workspace

#8721 file-search: fix not ignoring .git
  CHANGELOG.md
  packages/file-search/src/browser/quick-file-open.ts
  packages/file-search/src/node/file-search-service-impl.spec.ts
  packages/file-search/src/node/file-search-service-impl.ts
Labels: bug, file search, quality

#8733 Remove dependencies pulled in when writing to output channels
  packages/output/src/browser/output-contribution.ts
  packages/output/src/browser/output-frontend-module.ts
  packages/output/src/common/output-channel.ts
Labels: extensibility, output

#8725 Authentication Plugin API fixes
  packages/core/src/browser/authentication-service.ts
  packages/plugin-ext/src/main/browser/authentication-main.ts
Labels: Team: Che-Plugins, plug-in system, vscode

#8744 Enabled the sourcemaps for `monaco-editor.*`.
  dev-packages/application-manager/src/generator/webpack-generator.ts
Labels: monaco

#8646 [SIW] Add support to search in outside workspace content
  packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx
  packages/search-in-workspace/src/browser/search-in-workspace-service.ts
Labels: search in workspace

#8741 [@theia/console] Remove workaround that is no longer necessary
  packages/console/package.json
  packages/console/src/browser/ansi-console-item.tsx
  yarn.lock
Labels: dependencies, quality

#8729 Render initial preview for empty documents
  packages/preview/src/browser/preview-widget.ts
Labels: preview

#8674 8428-stop-hosted-instance
  packages/plugin-dev/src/node/hosted-instance-manager.ts
  packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts
  packages/plugin-ext/src/hosted/node/hosted-plugin.ts
Labels: bug, plug-in system

#8770 Update eslint to the latest version
  configs/errors.eslintrc.json
  package.json
  packages/callhierarchy/src/common/glob.ts
  packages/callhierarchy/src/common/paths.ts
  packages/filesystem/src/browser/file-service.ts
  packages/filesystem/src/common/remote-file-system-provider.ts
  packages/filesystem/src/node/disk-file-system-provider.ts
  packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts
  packages/plugin-ext/src/plugin/file-system-event-service-ext-impl.ts
  packages/plugin-ext/src/plugin/node/debug/debug.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  yarn.lock
Labels: dependencies, linting

#8756 Apply problem matchers specified by task provider
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/plugin/type-converters.ts
Labels: tasks, vscode

#8784 documentation: updated changelog for 1.8.0
  CHANGELOG.md
Labels: documentation
