Repository eclipse-theia/theia, pull requests merged in 2020-08, with the labels that each got.

#8280 Upgrade vscode-ripgrep's yarn.lock entry so we pick-up latest
  .travis.yml
  CHANGELOG.md
  yarn.lock
Labels: dependencies

#8256 [keybinding] Duplicate keybinding for opening the preferences widget and deleting file on navigator
  packages/navigator/src/browser/navigator-contribution.ts
  packages/preferences/src/browser/preferences-contribution.ts
Labels: keybindings

#8228 navigator: fix explorer 'open' command
  packages/core/src/browser/common-frontend-contribution.ts
  packages/navigator/src/browser/navigator-contribution.ts
  packages/navigator/src/browser/navigator-widget.tsx
Labels: bug, menus, navigator

#8156 core: add support for badge decorations
  packages/core/src/browser/shell/tab-bar-decorator.ts
  packages/core/src/browser/shell/tab-bars.ts
  packages/core/src/browser/style/notification.css
  packages/core/src/browser/style/tabs.css
  packages/core/src/browser/widget-decoration.ts
  packages/markers/src/browser/problem/problem-frontend-module.ts
  packages/markers/src/browser/problem/problem-widget-tab-bar-decorator.ts
  packages/scm/src/browser/decorations/scm-tab-bar-decorator.ts
  packages/scm/src/browser/scm-frontend-module.ts
Labels: core, markers, scm

#8231 scm: add api integration tests
  examples/api-tests/src/scm.spec.js
  packages/scm/src/browser/scm-widget.tsx
Labels: scm, test

#8279 documentation: update individual extension readmes
  dev-packages/application-manager/README.md
  dev-packages/application-package/README.md
  dev-packages/cli/README.md
  dev-packages/electron/README.md
  dev-packages/ext-scripts/README.md
  examples/api-samples/README.md
  packages/callhierarchy/README.md
  packages/console/README.md
  packages/core/README.md
  packages/debug/README.md
  packages/editor-preview/README.md
  packages/editor/README.md
  packages/file-search/README.md
  packages/filesystem/README.md
  packages/getting-started/README.md
  packages/git/README.md
  packages/keymaps/README.md
  packages/markers/README.md
  packages/messages/README.md
  packages/metrics/README.md
  packages/mini-browser/README.md
  packages/monaco/README.md
  packages/navigator/README.md
  packages/outline-view/README.md
  packages/output/README.md
  packages/plugin-dev/README.md
  packages/plugin-ext-vscode/README.md
  packages/plugin-ext/README.md
  packages/plugin-metrics/README.md
  packages/plugin/README.md
  packages/preferences/README.md
  packages/preview/README.md
  packages/process/README.md
  packages/scm-extra/README.md
  packages/scm/README.md
  packages/search-in-workspace/README.md
  packages/task/README.md
  packages/terminal/README.md
  packages/typehierarchy/README.md
  packages/userstorage/README.md
  packages/variable-resolver/README.md
  packages/vsx-registry/README.md
  packages/workspace/README.md
Labels: documentation

#8298 tree indent guidelines support
  packages/core/src/browser/common-frontend-contribution.ts
  packages/core/src/browser/core-preferences.ts
  packages/core/src/browser/style/tree.css
  packages/core/src/browser/tree/tree-widget.tsx
Labels: tree

#8187 [Plugin-API] Apply ResourceLabelFormatter API
  packages/core/src/browser/label-provider.ts
  packages/core/src/browser/test/mock-env-variables-server.ts
  packages/core/src/common/label-protocol.ts
  packages/core/src/common/path.spec.ts
  packages/core/src/common/path.ts
  packages/editor/src/browser/editor-widget-factory.ts
  packages/filesystem/src/common/filesystem-utils.spec.ts
  packages/filesystem/src/common/filesystem-utils.ts
  packages/getting-started/src/browser/getting-started-widget.tsx
  packages/markers/src/browser/marker-tree-label-provider.spec.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/common/plugin-protocol.ts
  packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts
  packages/plugin-ext/src/main/browser/label-service-main.ts
  packages/plugin-ext/src/main/browser/main-context.ts
  packages/plugin-ext/src/main/browser/plugin-contribution-handler.ts
  packages/plugin-ext/src/plugin/label-service.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin/src/theia-proposed.d.ts
  packages/workspace/src/browser/quick-open-workspace.ts
  packages/workspace/src/browser/workspace-uri-contribution.spec.ts
  packages/workspace/src/browser/workspace-uri-contribution.ts
Labels: CQ Required, plug-in system, vscode

#8320 list `onFileSystem` activation event as supported
  packages/plugin-ext/src/plugin/plugin-manager.ts
Labels: vscode

#8283 Removed getScopedKeybindingsForCommand (no references)
  CHANGELOG.md
  packages/core/src/browser/keybinding.ts
Labels: keybindings, quality

#8331 Remove tasks start and exit with code 0 notifications
  packages/task/src/browser/task-service.ts
Labels: tasks

#8316 [explorer]: Badge count for dirty editors
  packages/navigator/src/browser/navigator-frontend-module.ts
  packages/navigator/src/browser/navigator-tab-bar-decorator.ts
Labels: badge, navigator

#8342 [badge]: Badge decoration for active debug sessions
  packages/core/src/browser/frontend-application-module.ts
  packages/core/src/browser/shell/tab-bar-decorator.ts
  packages/debug/src/browser/debug-frontend-module.ts
  packages/debug/src/browser/debug-tab-bar-decorator.ts
Labels: badge, debug

#8347 don't swallow failed plugin activation error
  packages/plugin-ext/src/plugin/plugin-manager.ts
Labels: vscode

#8315 cli: use `decompress` to decompress plugins
  dev-packages/cli/package.json
  dev-packages/cli/src/download-plugins.ts
  yarn.lock
Labels: dependencies, theia-cli

#8348 release in memory resource based on reference counting
  packages/core/src/common/resource.ts
Labels: json, tasks

#8294 security: update 'decompress' dependency
  CHANGELOG.md
  packages/plugin-ext/package.json
  yarn.lock
Labels: dependencies, security

#8264 [preferences]: Input field validation for numerical inputs
  packages/preferences/src/browser/style/index.css
  packages/preferences/src/browser/views/components/preference-number-input.tsx
Labels: preferences

#8355 GH-8350: Fixed bogus app config defaults.
  dev-packages/application-package/package.json
  dev-packages/application-package/src/application-package.ts
  dev-packages/application-package/src/application-props.ts
Labels: core

#8247 Add collapse-all command for SCM tree mode
  packages/scm/src/browser/scm-contribution.ts
  packages/scm/src/browser/scm-widget.tsx
Labels: enhancement, scm

#8366 deploy: fix deploy stage during CI
  .travis.yml
Labels: bug, ci

#8367 deploy: fix deploy stage during CI
  .travis.yml
Labels: bug, ci

#8359 stream webview resources to avoid blocking a web socket
  CHANGELOG.md
  packages/plugin-ext/src/main/browser/plugin-ext-frontend-module.ts
  packages/plugin-ext/src/main/browser/webview/webview.ts
  packages/plugin-ext/src/main/common/webview-protocol.ts
  packages/plugin-ext/src/main/node/plugin-ext-backend-module.ts
  packages/plugin-ext/src/main/node/webview-resource-loader-impl.ts
Labels: performance, webviews

#8369 fix CHANGELOG rendering on GitHub
  CHANGELOG.md
Labels: documentation

#8376 changelog: add release dates
  CHANGELOG.md
Labels: documentation

#8377 Fixed submenu ordering.
  examples/api-samples/src/browser/menu/sample-menu-contribution.ts
  packages/core/src/common/menu.ts
Labels: menus

#8385 plugin-ext: fix local-dir resolution
  packages/plugin-ext/src/main/node/resolvers/plugin-local-dir-resolver.ts
Labels: OS/Windows, vscode

#8345 [electron]: Fixed the window reloading issue.
  dev-packages/application-manager/src/generator/frontend-generator.ts
Labels: electron

#8381 set default value of colorTheme and iconTheme preference
  CHANGELOG.md
  dev-packages/application-manager/src/generator/frontend-generator.ts
  dev-packages/application-package/src/application-props.ts
  dev-packages/cli/README.md
  packages/core/src/browser/common-frontend-contribution.ts
  packages/core/src/browser/connection-status-service.spec.ts
  packages/core/src/browser/core-preferences.ts
  packages/core/src/browser/icon-theme-contribution.ts
  packages/core/src/browser/icon-theme-service.ts
  packages/core/src/browser/preferences/preference-proxy.spec.ts
  packages/core/src/browser/preferences/preference-service.spec.ts
  packages/core/src/browser/theming.ts
  packages/editor-preview/src/browser/editor-preview-factory.spec.ts
  packages/git/src/browser/git-repository-provider.spec.ts
  packages/markers/src/browser/marker-tree-label-provider.spec.ts
  packages/navigator/src/browser/navigator-diff.spec.ts
  packages/preferences/src/browser/util/preference-tree-generator.spec.ts
  packages/preview/src/browser/markdown/markdown-preview-handler.spec.ts
  packages/workspace/src/browser/workspace-frontend-contribution.spec.ts
Labels: python, theming, vscode

#8382 fix debug exception height computation
  packages/debug/src/browser/editor/debug-editor-model.ts
  packages/debug/src/browser/editor/debug-exception-widget.tsx
Labels: debug

#8386 [plugin] return cloned preference to serialize not a clone function
  packages/plugin-ext/src/plugin/preference-registry.ts
Labels: ruby, vscode

#8396 don't activate plugin eagerly on unsupported event
  packages/plugin-ext/src/plugin/plugin-manager.ts
Labels: python, vscode

#8362 GH-8361: Fixed editor resizing issue in Output.
  packages/output/src/browser/output-widget.tsx
Labels: output

#8419 GH-8416: Fixed the menu widget layout.
  packages/core/src/browser/style/menus.css
Labels: shell

#8397 Convert stylesheet.innerHTML to stylesheet.innerText
  packages/plugin-ext/src/main/browser/plugin-icon-theme-service.ts
Labels: plug-in system, security

#8372 fix #8226: Add a settings menu on left sidebar bottom
  packages/core/src/browser/common-frontend-contribution.ts
  packages/core/src/browser/frontend-application-module.ts
  packages/core/src/browser/shell/index.ts
  packages/core/src/browser/shell/side-panel-handler.ts
  packages/core/src/browser/shell/sidebar-bottom-menu-widget.tsx
  packages/core/src/browser/style/sidepanel.css
  packages/core/src/common/menu.ts
  packages/keymaps/src/browser/keymaps-frontend-contribution.ts
  packages/preferences/src/browser/preferences-contribution.ts
Labels: enhancement, preferences

#8436 documentation: update changelog for 1.5.0 release
  CHANGELOG.md
Labels: documentation

#8420 GH-8413: Execute the command if has active handler
  packages/core/src/browser/keybinding.ts
Labels: keybindings

#8424 Fix issue with default value in workspaceState/globalState
  packages/plugin-ext/src/plugin/plugin-storage.ts
Labels: vscode

#8269 Added a way to unregister keybindings for a command
  packages/core/src/browser/keybinding.spec.ts
  packages/core/src/browser/keybinding.ts
Labels: keybindings

#8439 repo: yarn upgrade
  packages/git/src/browser/git-repository-provider.ts
  packages/preview/src/browser/markdown/markdown-preview-handler.ts
  yarn.lock
Labels: dependencies
