Repository eclipse-theia/theia, pull requests merged in 2020-04, with the labels that each got.

#7265 add integration tests for typescript language
  CHANGELOG.md
  dev-packages/application-manager/src/expose-loader.ts
  examples/api-tests/src/api-tests.d.ts
  examples/api-tests/src/launch-preferences.spec.js
  examples/api-tests/src/menus.spec.js
  examples/api-tests/src/monaco-api.spec.js
  examples/api-tests/src/saveable.spec.js
  examples/api-tests/src/shell.spec.js
  examples/api-tests/src/typescript.spec.js
  examples/api-tests/src/views.spec.js
  examples/browser/.eslintrc.js
  examples/browser/package.json
  packages/core/src/browser/keybinding.ts
  packages/core/src/browser/progress-status-bar-item.ts
  packages/core/src/browser/saveable.ts
  packages/core/src/browser/shell/application-shell.ts
  packages/core/src/browser/shell/side-panel-handler.ts
  packages/core/src/browser/shell/tab-bars.ts
  packages/core/src/browser/widget-open-handler.ts
  packages/core/src/common/reference.spec.ts
  packages/core/src/common/reference.ts
  packages/languages/src/browser/language-client-services.ts
  packages/monaco/src/typings/monaco/index.d.ts
  packages/plugin-ext/src/common/plugin-api-rpc-model.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/hosted/browser/hosted-plugin.ts
  packages/plugin-ext/src/main/browser/debug/debug-main.ts
  packages/plugin-ext/src/main/browser/languages-main.ts
  packages/plugin-ext/src/main/browser/webview/webview.ts
  packages/plugin-ext/src/plugin/languages.ts
  packages/plugin-ext/src/plugin/plugin-manager.ts
  tsconfig.json
Labels: monaco, plug-in system, test

#7424 added api management guideline
  doc/api-management.md
Labels: documentation

#7468 Null-check call result rather than function itself
  examples/api-tests/src/monaco-api.spec.js
  packages/monaco/src/browser/monaco-resolved-keybinding.ts
Labels: dependencies, electron

#7455 support modifying existing problem matchers
  packages/task/src/browser/task-problem-matcher-registry.ts
  packages/task/src/browser/task-schema-updater.ts
  packages/task/src/browser/task-service.ts
  packages/task/src/common/task-protocol.ts
Labels: tasks, vscode

#7439 vsx: update extension information in the extension-editor
  packages/vsx-registry/src/browser/style/index.css
Labels: ui/ux, vsx-registry

#7461 #7451 [showSaveDialog] incompatible with VSCode
  packages/plugin-ext/src/main/browser/dialogs-main.ts
Labels: vscode

#7454 support presentation.showReuseMessage & clear in task config
  packages/task/src/browser/task-schema-updater.ts
  packages/task/src/browser/task-terminal-widget-manager.ts
  packages/task/src/common/task-protocol.ts
Labels: tasks, vscode

#6836 process/task/terminal: refactor escaping/quoting
  CHANGELOG.md
  package.json
  packages/core/src/node/backend-application.ts
  packages/debug/src/browser/debug-session-contribution.ts
  packages/debug/src/browser/debug-session.tsx
  packages/process/package.json
  packages/process/src/common/process-common-module.ts
  packages/process/src/common/shell-command-builder.slow-spec.ts
  packages/process/src/common/shell-command-builder.ts
  packages/process/src/common/shell-quoting.spec.ts
  packages/process/src/common/shell-quoting.ts
  packages/process/src/common/tests/$weird(),file=name.js
  packages/process/src/common/tests/white space.js
  packages/process/src/node/process.ts
  packages/process/src/node/terminal-process.spec.ts
  packages/process/src/node/terminal-process.ts
  packages/task/src/common/process/task-protocol.ts
  packages/task/src/node/process/process-task-runner.ts
  packages/task/src/node/task-server.slow-spec.ts
  packages/task/src/node/test/task-test-container.ts
  packages/task/test-resources/compare.js
  packages/task/test-resources/test-arguments-0.js
  packages/task/test-resources/test-arguments-1.js
  packages/task/test-resources/test-arguments-2.js
  packages/terminal/src/browser/base/terminal-widget.ts
  packages/terminal/src/browser/terminal-widget-impl.ts
  packages/terminal/src/common/base-terminal-protocol.ts
  packages/terminal/src/node/base-terminal-server.ts
  scripts/prepare-travis.js
  yarn.lock
Labels: debug, process, quality, tasks

#7492 Disable git initialize repository when no open workspace
  packages/git/src/browser/git-contribution.ts
Labels: git

#7452 set focus to terminal that the attached task is running from
  packages/task/src/browser/task-service.ts
  packages/terminal/src/browser/base/terminal-service.ts
  packages/terminal/src/browser/terminal-frontend-contribution.ts
Labels: tasks, terminal

#7485 refactor the task terminal widget option
  packages/task/src/browser/task-service.ts
  packages/task/src/browser/task-terminal-widget-manager.ts
Labels: tasks

#7479 Prevent F1 and CtrlCmd+P hotkey in webview iframe
  packages/plugin-ext/src/main/browser/webview/pre/main.js
Labels: bug, webviews

#7453 only run selected texts in a user terminal
  packages/task/src/browser/task-service.ts
Labels: tasks, terminal

#7526 [menu] don't stingify class instances
  packages/core/src/browser/menu/browser-menu-plugin.ts
Labels: menus

#7449 [DialogBox] : Improve display for remove folder from workspace
  packages/core/src/browser/style/dialog.css
  packages/workspace/src/browser/workspace-commands.ts
Labels: dialogs, ui/ux, workspace

#7517 Parse DAP messages to match VS Code API
  packages/plugin-ext/src/plugin/node/debug/plugin-debug-adapter-session.ts
Labels: debug, vscode

#7552 Mark only those commands ran using quick menu as recent
  packages/core/src/browser/quick-open/quick-command-service.ts
  packages/core/src/common/command.spec.ts
  packages/core/src/common/command.ts
Labels: commands

#7553 save scope as part of the `TaskService.lastTask`
  packages/task/src/browser/provided-task-configurations.ts
  packages/task/src/browser/task-service.ts
Labels: tasks

#7532 keymaps: adjust keybindings-widget
  packages/keymaps/src/browser/keybindings-widget.tsx
Labels: commands, keybindings, ui/ux

#7564 Bump VS Code API version to 1.44.0
  packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts
Labels: vscode

#7535 Bumped nsfw to 1.2.9
  packages/core/package.json
  yarn.lock
Labels: filesystem

#7562 core: fix recently used quick-commands
  packages/core/src/browser/quick-open/quick-command-service.ts
  packages/core/src/common/command.spec.ts
  packages/core/src/common/command.ts
Labels: commands

#7544 plugin-ext: late textmate grammar activation
  packages/plugin-ext/src/main/browser/plugin-contribution-handler.ts
Labels: bug, textmate

#7548 fix presentation.reveal & focus for detected tasks
  CHANGELOG.md
  packages/task/src/browser/provided-task-configurations.ts
  packages/task/src/browser/task-service.ts
  packages/task/src/common/task-protocol.ts
Labels: tasks

#7569 Bind EditorCommandContribution and EditorMenuContribution toSelf
  packages/editor/src/browser/editor-frontend-module.ts
Labels: editor

#7565 Don't paste to active editor when a tab is closed by mouse wheel click
  packages/core/src/browser/shell/tab-bars.ts
Labels: shell

#7563 Implemented more vscode.executeXXX commands
  packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts
  packages/plugin-ext/src/plugin/known-commands.ts
Labels: vscode

#7574 support user-defined labels for detected tasks
  packages/task/src/browser/task-configurations.ts
  packages/task/src/browser/task-definition-registry.ts
  packages/task/src/browser/task-name-resolver.ts
  packages/task/src/browser/task-schema-updater.ts
  packages/task/src/browser/task-service.ts
Labels: tasks

#7578 application-package: show warning if user set unknown target and explicitly set it as browser
  dev-packages/application-package/src/application-package.spec.ts
  dev-packages/application-package/src/application-package.ts
  dev-packages/application-package/src/application-props.ts
Labels: theia-cli

#7534 Implementation of SelectionRange and SelectionRangeProvider API
  packages/plugin-ext/src/common/plugin-api-rpc-model.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/languages-main.ts
  packages/plugin-ext/src/plugin/languages.ts
  packages/plugin-ext/src/plugin/languages/selection-range.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/type-converters.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
Labels: vscode

#7503 support presentation.echo in task config
  packages/task/src/browser/task-schema-updater.ts
  packages/task/src/browser/task-service.ts
  packages/task/src/browser/task-terminal-widget-manager.ts
  packages/task/src/common/process/task-protocol.ts
  packages/task/src/common/task-protocol.ts
  packages/task/src/node/process/process-task-runner.ts
  packages/task/src/node/process/process-task.ts
Labels: tasks

#7595 Remove unused injections of ResourceProvider
  packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts
  packages/task/src/browser/task-configurations.ts
Labels: tasks, vscode

#7610 Fix syntax highlighting by bumping onigasm
  packages/monaco/package.json
  yarn.lock
Labels: vscode

#7549 [output] add severity/color to appendLine method
  CHANGELOG.md
  examples/api-samples/compile.tsconfig.json
  examples/api-samples/package.json
  examples/api-samples/src/browser/api-samples-frontend-module.ts
  examples/api-samples/src/browser/output/sample-output-channel-with-severity.ts
  packages/output/src/browser/output-widget.tsx
  packages/output/src/browser/style/output.css
  packages/output/src/common/output-channel.ts
Labels: output

#7618 respect editor.maxTokenizationLineLength preference
  packages/monaco/src/browser/textmate/monaco-textmate-service.ts
  packages/monaco/src/browser/textmate/textmate-tokenizer.ts
Labels: monaco, textmate, vscode

#7630 [gitpod] trigger rebuild to pick upstream image changes
  .gitpod.dockerfile
Labels: gitpod

#7639 repo: update the repository's issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: contributor experience

#7640 Documentation improvement
  doc/Developing.md
Labels: documentation

#7601 plugins: sort plugins in the plugins-view
  packages/plugin-ext/src/main/browser/plugin-ext-widget.tsx
Labels: plug-in system, ui/ux

#7641 cli: improve plugin download logic
  dev-packages/cli/src/download-plugins.ts
  dev-packages/cli/src/theia.ts
Labels: ci, plug-in system, theia-cli

#7636 [hosted plugin] fix no indication for selecting an invalid node.js project
  packages/plugin-dev/src/node/hosted-instance-manager.ts
Labels: plug-in system

#7583 Fix plugin icon URLs in electron & Fix custom icon themes
  CHANGELOG.md
  packages/plugin-ext-vscode/src/node/scanner-vscode.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/common/plugin-protocol.ts
  packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts
  packages/plugin-ext/src/main/browser/plugin-icon-theme-service.ts
  packages/plugin-ext/src/main/browser/plugin-shared-style.ts
  packages/plugin-ext/src/main/browser/view/plugin-view-registry.ts
Labels: electron, vscode

#7642 feat(plugin): Use product applicationName to return the value to plugins env.appName
  CHANGELOG.md
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/hosted/browser/hosted-plugin.ts
  packages/plugin-ext/src/plugin/env.ts
  packages/plugin-ext/src/plugin/plugin-manager.ts
Labels: enhancement, vscode

#7500 plugin: fix message-service
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/dialogs/modal-notification.ts
  packages/plugin-ext/src/main/browser/dialogs/style/modal-notification.css
  packages/plugin-ext/src/main/browser/message-registry-main.ts
  packages/plugin-ext/src/plugin/message-registry.ts
Labels: bug, notifications, vscode

#7598 workspace: normalize paths of workspace roots
  packages/workspace/src/browser/workspace-service.spec.ts
  packages/workspace/src/browser/workspace-service.ts
Labels: multi-root, terminal, workspace

#7656 feat(branding): Change default name to 'Eclipse Theia' instead of 'Theia'
  dev-packages/application-package/src/application-props.ts
Labels: theia-cli

#7658 Add devfile to develop Theia in Che
  devfile.yaml
Labels: Team: Che-Editors

#7649 vsx: Download Open VSX extensions over HTTPS
  package.json
Labels: builtins

#7650 trivial: Prefer HTTPS over HTTP for various links
  .vscode/extensions.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  NOTICE.md
  doc/Developing.md
Labels: documentation

#7667 [cli] refine test filter to exclude only test args
  dev-packages/cli/src/theia.ts
Labels: test

#7663 Added meta tag to enable fullscreen experience on iOS devices
  dev-packages/application-manager/src/generator/frontend-generator.ts
Labels: ipad

#7330 theming: fix decoration color theming
  packages/editor/src/browser/decorations/editor-decoration.ts
  packages/scm/src/browser/dirty-diff/dirty-diff-decorator.ts
  packages/scm/src/browser/scm-contribution.ts
  packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx
Labels: scm, search in workspace, theming

#7677 cli: replace request package
  dev-packages/cli/package.json
  dev-packages/cli/src/download-plugins.ts
  yarn.lock
Labels: enhancement, theia-cli

#7627 Change successExitCodes and ExpectedErrors to arrays
  packages/git/src/common/git.ts
  packages/git/src/node/dugite-git.spec.ts
  packages/git/src/node/dugite-git.ts
Labels: git

#7660 Added preferences for shell & shell arguments
  packages/terminal/src/browser/terminal-preferences.ts
  packages/terminal/src/browser/terminal-widget-impl.ts
  packages/terminal/src/common/shell-terminal-protocol.ts
  packages/terminal/src/node/shell-process.ts
Labels: preferences, terminal

#7694 outline: fix keybinding collision on linux
  packages/outline-view/src/browser/outline-view-contribution.ts
Labels: OS/Linux, keybindings, outline

#7695 debug: fix vscode-builtin-node-debug
  package.json
Labels: bug, builtins, debug

#7688 multi-root: fix statusbar color
  packages/workspace/src/browser/workspace-frontend-contribution.ts
Labels: multi-root

#7692 ensure that only one context menu can be opened
  examples/api-tests/src/menus.spec.js
  packages/core/src/browser/context-menu-renderer.ts
  packages/core/src/browser/menu/browser-context-menu-renderer.ts
  packages/core/src/electron-browser/menu/electron-context-menu-renderer.ts
Labels: menus, test

#7704 Removed obsolete `@types/p-debounce` dependency.
  packages/core/package.json
  packages/debug/package.json
  packages/scm/package.json
  yarn.lock
Labels: dependencies

#7705 documentation: updated changelog for v1.1.0 release
  CHANGELOG.md
Labels: documentation

#7711 script: fixed the 'check-publish' script
  scripts/check-publish.js
Labels: bug
