Repository eclipse-theia/theia, pull requests merged in 2022-02, with the labels that each got.

#10469 Properly handle debug console completion
  packages/debug/src/browser/console/debug-console-contribution.tsx
  packages/debug/src/browser/console/debug-console-session.ts
  packages/debug/src/browser/debug-session.tsx
Labels: debug, console

#10694 Fix sorting problem in QuickFileOpenService
  examples/api-tests/src/file-search.spec.js
  packages/file-search/src/browser/quick-file-open.ts
Labels: file search

#10473 Implement light-weight Workspace Trust API for plugins
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/workspace-main.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/workspace.ts
  packages/plugin/src/theia.d.ts
  packages/preferences/src/browser/util/preference-tree-generator.ts
  packages/workspace/src/browser/index.ts
  packages/workspace/src/browser/workspace-frontend-module.ts
  packages/workspace/src/browser/workspace-trust-preferences.ts
  packages/workspace/src/browser/workspace-trust-service.ts
Labels: vscode

#10705 Support VSCode WebviewView API
  packages/editor/src/browser/editor-preferences.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/common/plugin-protocol.ts
  packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts
  packages/plugin-ext/src/main/browser/main-context.ts
  packages/plugin-ext/src/main/browser/view/plugin-view-registry.ts
  packages/plugin-ext/src/main/browser/webview-views/webview-views-main.ts
  packages/plugin-ext/src/main/browser/webview-views/webview-views.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/webview-views.ts
  packages/plugin-ext/src/plugin/webviews.ts
  packages/plugin/src/theia.d.ts
Labels: vscode, webviews

#10704 Remove global shortcuts from Electron, use WindowService for reload
  CHANGELOG.md
  packages/core/src/electron-browser/menu/electron-menu-contribution.ts
  packages/core/src/electron-main/electron-main-application.ts
Labels: terminal, electron

#10665 Handle Language Overrides in `setPreference`
  examples/api-tests/src/launch-preferences.spec.js
  examples/api-tests/src/preferences.spec.js
  packages/core/src/browser/preferences/preference-language-override-service.ts
  packages/preferences/src/browser/abstract-resource-preference-provider.ts
  packages/preferences/src/browser/workspace-file-preference-provider.ts
Labels: preferences

#10720 Add browser compound launch
  .vscode/launch.json
Labels: contributor experience

#10355 repo: upgrade to TypeScript 4
  .vscode/settings.json
  dev-packages/localization-manager/package.json
  doc/Migration.md
  license-check-baseline.json
  package.json
  packages/core/src/browser/authentication-service.ts
  packages/core/src/browser/shell/tab-bars.ts
  packages/core/src/browser/source-tree/source-tree.ts
  packages/core/src/browser/view-container.ts
  packages/core/src/common/event.ts
  packages/core/src/common/messaging/proxy-factory.ts
  packages/core/src/node/messaging/ipc-connection-provider.ts
  packages/filesystem/src/node/download/directory-archiver.spec.ts
  packages/git/src/node/git-repository-watcher.ts
  packages/monaco/src/browser/monaco-editor-provider.ts
  packages/plugin-ext/src/common/plugin-api-rpc-model.ts
  packages/plugin-ext/src/hosted/node/plugin-reader.ts
  packages/plugin-ext/src/main/browser/view-column-service.ts
  packages/plugin-ext/src/main/node/paths/plugin-paths-service.ts
  packages/preferences/src/browser/util/preference-tree-generator.ts
  packages/preview/src/browser/markdown/markdown-preview-handler.ts
  packages/process/src/node/multi-ring-buffer.spec.ts
  packages/process/src/node/raw-process.spec.ts
  packages/scm-extra/src/browser/history/scm-history-widget.tsx
  packages/search-in-workspace/src/node/ripgrep-search-in-workspace-server.slow-spec.ts
  packages/task/src/node/task-server.slow-spec.ts
  packages/terminal/src/node/terminal-backend-contribution.slow-spec.ts
  packages/typehierarchy/src/browser/tree/typehierarchy-tree.ts
  yarn.lock
Labels: contributor experience, dependencies, potentially-breaking

#10722 Update dugite-extra, remove `--ignore-engines`
  .github/workflows/build.yml
  .gitpod.dockerfile
  doc/Developing.md
  packages/git/package.json
  yarn.lock
Labels: dependencies

#10729 repo: upgrade `typedoc` for typescript 4.5
  configs/typedoc.json
  package.json
  yarn.lock
Labels: documentation, dependencies

#10718 debug: remove plugin import
  packages/plugin-ext/src/plugin/node/debug/plugin-debug-adapter-starter.ts
  packages/plugin-ext/src/plugin/node/debug/plugin-inline-debug-adapter.ts
Labels: plug-in system, debug

#10725 yarn upgrade + dep fix
  doc/Developing.md
  examples/api-tests/src/typescript.spec.js
  license-check-baseline.json
  packages/core/README.md
  packages/debug/src/browser/style/index.css
  packages/electron/README.md
  packages/electron/package.json
  packages/plugin-ext/src/main/electron-browser/webview/electron-webview-widget-factory.ts
  scripts/check_git_status.sh
  yarn.lock
Labels: quality, dependencies

#10708 Run playwright tests in CI
  .github/workflows/playwright.yml
  examples/playwright/configs/playwright.ci.config.ts
  examples/playwright/package.json
  package.json
Labels: ci, test

#10749 repo: fix typedoc config
  configs/typedoc.json
Labels: ci, documentation

#10711 Fix handling malformed recentworkspace.json
  packages/workspace/src/node/default-workspace-server.spec.ts
  packages/workspace/src/node/default-workspace-server.ts
Labels: workspace

#10754 #10696 Complete createStatusBarItem in window namespace from VSCode API
  CHANGELOG.md
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/status-bar-message-registry.ts
  packages/plugin-ext/src/plugin/status-bar/status-bar-item.ts
  packages/plugin/src/theia.d.ts
Labels: vscode

#10695 Add theia plugin API documentation
  README.md
  doc/Plugin-API.md
  doc/images/plugin-api-diagram.drawio.xml
  doc/images/plugin-api-diagram.png
Labels: documentation

#10514 Refactor communication layer to use socket.io
  CHANGELOG.md
  doc/Migration.md
  packages/core/package.json
  packages/core/src/browser/frontend-application-bindings.ts
  packages/core/src/browser/messaging/messaging-frontend-module.ts
  packages/core/src/browser/messaging/ws-connection-provider.ts
  packages/core/src/common/message-service.ts
  packages/core/src/electron-node/token/electron-token-messaging-contribution.ts
  packages/core/src/node/messaging/http-websocket-adapter.ts
  packages/core/src/node/messaging/messaging-backend-module.ts
  packages/core/src/node/messaging/messaging-contribution.ts
  packages/core/src/node/messaging/messaging-listeners.ts
  packages/core/src/node/messaging/messaging-service.ts
  packages/core/src/node/messaging/test/test-web-socket-channel.ts
  yarn.lock
Labels: messaging, decision_needed

#10757 core: bump `socket.io` dependency
  packages/core/package.json
  yarn.lock
Labels: messaging, security, dependencies

#10719 Align preference and notification styling with VSCode
  packages/core/src/browser/common-frontend-contribution.ts
  packages/messages/src/browser/notification-component.tsx
  packages/messages/src/browser/style/notifications.css
  packages/preferences/src/browser/style/index.css
  packages/preferences/src/browser/views/components/preference-node-renderer.ts
Labels: preferences, notifications, ui/ux

#10759 typedoc: fix `out` directory
  configs/typedoc.json
Labels: documentation

#10730 Add CodeActionProvider#resolveCodeAction to plugin API
  CHANGELOG.md
  packages/plugin-ext/src/common/plugin-api-rpc-model.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/languages-main.ts
  packages/plugin-ext/src/plugin/languages.ts
  packages/plugin-ext/src/plugin/languages/code-action.ts
  packages/plugin/src/theia.d.ts
Labels: vscode

#10717 repo: cleanup dependencies
  dev-packages/cli/package.json
  packages/callhierarchy/package.json
  packages/callhierarchy/tsconfig.json
  packages/debug/package.json
  packages/debug/tsconfig.json
  packages/editor/package.json
  packages/file-search/package.json
  packages/file-search/src/common/monaco.d.ts
  packages/file-search/tsconfig.json
  packages/filesystem/package.json
  packages/getting-started/package.json
  packages/getting-started/tsconfig.json
  packages/git/package.json
  packages/git/tsconfig.json
  packages/keymaps/package.json
  packages/keymaps/tsconfig.json
  packages/monaco/package.json
  packages/monaco/tsconfig.json
  packages/outline-view/package.json
  packages/plugin-dev/package.json
  packages/plugin-dev/tsconfig.json
  packages/preferences/package.json
  packages/preview/src/browser/markdown/markdown-preview-handler.ts
  packages/task/package.json
  packages/task/tsconfig.json
  packages/terminal/package.json
  packages/terminal/src/common/monaco.d.ts
  packages/terminal/tsconfig.json
  packages/vsx-registry/package.json
  packages/workspace/package.json
  yarn.lock
Labels: quality, dependencies

#10764 replace `ChangesStream` with `nano`
  dev-packages/application-package/package.json
  dev-packages/application-package/src/npm-registry.ts
  yarn.lock
Labels: security, dependencies

#10536 Fix `CopyWebpackPlugin` for missing `@theia/monaco`
  dev-packages/application-manager/src/generator/webpack-generator.ts
Labels: theia-cli

#10397 Add eslint rule for localization issues
  configs/errors.eslintrc.json
  dev-packages/private-eslint-plugin/README.md
  dev-packages/private-eslint-plugin/index.js
  dev-packages/private-eslint-plugin/package.json
  dev-packages/private-eslint-plugin/rules/localization-check.js
  packages/bulk-edit/src/browser/bulk-edit-tree/bulk-edit-tree-widget.tsx
  packages/core/src/browser/core-preferences.ts
  packages/core/src/browser/keyboard/browser-keyboard-frontend-contribution.ts
  packages/core/src/electron-browser/menu/electron-menu-contribution.ts
  packages/core/src/electron-browser/window/electron-window-preferences.ts
  packages/debug/src/node/vscode/vscode-debug-adapter-contribution.ts
  packages/editor/src/browser/editor-command.ts
  packages/editor/src/browser/editor-preferences.ts
  packages/external-terminal/src/electron-browser/external-terminal-preference.ts
  packages/file-search/src/browser/quick-file-open.ts
  packages/filesystem/src/browser/file-upload-service.ts
  packages/getting-started/src/browser/getting-started-widget.tsx
  packages/git/src/browser/git-contribution.ts
  packages/git/src/browser/git-quick-open-service.ts
  packages/git/src/common/git-model.ts
  packages/outline-view/src/browser/outline-view-widget.tsx
  packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts
  packages/plugin-ext/src/main/browser/authentication-main.ts
  packages/preferences/src/browser/preference-transaction-manager.ts
  packages/property-view/src/browser/resource-property-view/resource-property-view-tree-widget.tsx
  packages/scm-extra/src/browser/history/scm-history-widget.tsx
  packages/search-in-workspace/src/browser/search-in-workspace-factory.ts
  packages/search-in-workspace/src/browser/search-in-workspace-frontend-contribution.ts
  packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx
  packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx
  packages/terminal/src/browser/terminal-preferences.ts
  packages/vsx-registry/src/browser/vsx-extension-commands.ts
  packages/workspace/src/browser/workspace-commands.ts
  packages/workspace/src/browser/workspace-frontend-contribution.ts
  packages/workspace/src/browser/workspace-trust-preferences.ts
  yarn.lock
Labels: contributor experience, localization

#10721 Support VS Code Web extensions
  packages/plugin-ext-vscode/src/node/context/plugin-vscode-init-fe.ts
  packages/plugin-ext-vscode/src/node/plugin-reader.ts
  packages/plugin-ext-vscode/src/node/plugin-vscode-backend-module.ts
  packages/plugin-ext-vscode/src/node/scanner-vscode.ts
  packages/plugin-ext/src/common/plugin-protocol.ts
  packages/plugin-ext/src/hosted/browser/worker/worker-main.ts
Labels: vscode

#10747 Correctly expose extensionUri for frontend modules
  packages/core/src/browser/endpoint.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/plugin-manager.ts
Labels: vscode

#10600 Encapsulate Electron Window Logic - Allow Exit during Load
  CHANGELOG.md
  packages/core/src/browser/frontend-application-state.ts
  packages/core/src/common/frontend-application-state.ts
  packages/core/src/electron-browser/window/electron-frontend-application-state.ts
  packages/core/src/electron-browser/window/electron-window-module.ts
  packages/core/src/electron-common/messaging/electron-messages.ts
  packages/core/src/electron-main/electron-main-application-module.ts
  packages/core/src/electron-main/electron-main-application.ts
  packages/core/src/electron-main/electron-main-constants.ts
  packages/core/src/electron-main/event-utils.ts
  packages/core/src/electron-main/theia-electron-window.ts
Labels: electron, proposal

#10774 Add extensions example to plugin docs
  doc/Plugin-API.md
Labels: documentation, plug-in system

#10760 debug: fix `debuggingForeground` theming
  packages/debug/src/browser/style/index.css
Labels: theming, debug

#10761 core: update default loading animation
  packages/core/src/browser/style/index.css
Labels: theming, ui/ux

#10785 ci: lint once
  .github/workflows/ci-cd.yml
Labels: enhancement, ci, linting

#10773 core: remove `maxListeners` property from `Event`
  CHANGELOG.md
  packages/core/src/browser/authentication-service.ts
  packages/core/src/common/cancellation.ts
  packages/core/src/common/event.ts
  packages/plugin-ext/src/main/browser/menus/menus-contribution-handler.ts
Labels: core

#10779 re-exports: fix generated eol
  dev-packages/private-re-exports/src/bin-theia-re-exports.ts
Labels: OS/Windows, contributor experience

#10777 Implement `disabled`, `isPreferred` and `documentation` fields for code actions
  packages/plugin-ext/src/common/plugin-api-rpc-model.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/languages-main.ts
  packages/plugin-ext/src/plugin/languages.ts
  packages/plugin-ext/src/plugin/languages/code-action.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin-metrics/src/browser/plugin-metrics-languages-main.ts
  packages/plugin/src/theia.d.ts
Labels: vscode

#10784 Add missing property to CustomDocumentOpenContext
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/custom-editors/custom-editors-main.ts
  packages/plugin-ext/src/plugin/custom-editors.ts
  packages/plugin/src/theia.d.ts
Labels: vscode

#10782 Add machine translations for 12 languages
  dev-packages/cli/src/theia.ts
  dev-packages/localization-manager/src/common.ts
  dev-packages/localization-manager/src/deepl-api.ts
  dev-packages/localization-manager/src/localization-extractor.spec.ts
  dev-packages/localization-manager/src/localization-extractor.ts
  dev-packages/localization-manager/src/localization-manager.ts
  packages/callhierarchy/src/browser/callhierarchy-contribution.ts
  packages/callhierarchy/src/browser/callhierarchy-tree/callhierarchy-tree-widget.tsx
  packages/core/i18n/nls.cs.json
  packages/core/i18n/nls.de.json
  packages/core/i18n/nls.es.json
  packages/core/i18n/nls.fr.json
  packages/core/i18n/nls.hu.json
  packages/core/i18n/nls.it.json
  packages/core/i18n/nls.ja.json
  packages/core/i18n/nls.json
  packages/core/i18n/nls.pl.json
  packages/core/i18n/nls.pt-br.json
  packages/core/i18n/nls.pt-pt.json
  packages/core/i18n/nls.ru.json
  packages/core/i18n/nls.zh-cn.json
  packages/core/src/node/i18n/i18n-backend-module.ts
  packages/core/src/node/i18n/theia-localization-contribution.ts
  packages/debug/src/browser/debug-frontend-application-contribution.ts
  packages/editor/src/browser/editor-command.ts
  packages/git/src/browser/git-quick-open-service.ts
  packages/markers/src/browser/problem/problem-contribution.ts
  packages/monaco/src/browser/monaco-command.ts
  packages/plugin-ext/src/main/browser/plugin-ext-widget.tsx
  packages/plugin-ext/src/main/browser/plugin-frontend-view-contribution.ts
  packages/scm-extra/src/browser/history/scm-history-contribution.ts
  packages/scm/src/browser/scm-contribution.ts
  packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx
  packages/terminal/src/browser/terminal-widget-impl.ts
  packages/workspace/src/browser/workspace-commands.ts
  packages/workspace/src/browser/workspace-service.ts
Labels: localization

#10607 Validate Preferences Used in Editor
  packages/core/src/browser/frontend-application-bindings.ts
  packages/core/src/browser/preferences/index.ts
  packages/core/src/browser/preferences/injectable-preference-proxy.ts
  packages/core/src/browser/preferences/preference-contribution.ts
  packages/core/src/browser/preferences/preference-provider.ts
  packages/core/src/browser/preferences/preference-proxy.spec.ts
  packages/core/src/browser/preferences/preference-proxy.ts
  packages/core/src/browser/preferences/preference-service.ts
  packages/core/src/browser/preferences/preference-validation-service.spec.ts
  packages/core/src/browser/preferences/preference-validation-service.ts
  packages/core/src/browser/preferences/validated-preference-proxy.ts
  packages/core/src/common/json-schema.ts
  packages/core/src/common/preferences/preference-schema.ts
  packages/editor/src/browser/editor-preferences.ts
  packages/monaco/src/browser/monaco-editor-provider.ts
  packages/plugin-ext/src/common/plugin-protocol.ts
  packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts
  packages/preferences/src/browser/views/components/preference-select-input.ts
  packages/preferences/src/browser/views/preference-widget-bindings.ts
  packages/task/src/browser/task-definition-registry.spec.ts
  packages/task/src/browser/task-schema-updater.ts
Labels: preferences, monaco

#10731 Add global toolbar 🛠
  examples/api-samples/package.json
  examples/api-samples/src/browser/api-samples-frontend-module.ts
  examples/api-samples/src/browser/toolbar/sample-toolbar-contribution.css
  examples/api-samples/src/browser/toolbar/sample-toolbar-contribution.tsx
  examples/api-samples/src/browser/toolbar/sample-toolbar-defaults-override.ts
  examples/api-samples/tsconfig.json
  examples/browser/package.json
  examples/browser/tsconfig.json
  examples/electron/package.json
  examples/electron/tsconfig.json
  packages/core/src/browser/common-frontend-contribution.ts
  packages/core/src/browser/quick-input/quick-command-service.ts
  packages/core/src/browser/shell/application-shell.ts
  packages/core/src/browser/style/index.css
  packages/toolbar/.eslintrc.js
  packages/toolbar/README.md
  packages/toolbar/fetch-icons.js
  packages/toolbar/package.json
  packages/toolbar/src/browser/abstract-toolbar-contribution.tsx
  packages/toolbar/src/browser/application-shell-with-toolbar-override.ts
  packages/toolbar/src/browser/codicons.ts
  packages/toolbar/src/browser/font-awesome-icons.ts
  packages/toolbar/src/browser/package.spec.ts
  packages/toolbar/src/browser/style/toolbar.css
  packages/toolbar/src/browser/toolbar-command-contribution.ts
  packages/toolbar/src/browser/toolbar-command-quick-input-service.ts
  packages/toolbar/src/browser/toolbar-constants.ts
  packages/toolbar/src/browser/toolbar-controller.ts
  packages/toolbar/src/browser/toolbar-defaults.ts
  packages/toolbar/src/browser/toolbar-frontend-module.ts
  packages/toolbar/src/browser/toolbar-icon-selector-dialog.tsx
  packages/toolbar/src/browser/toolbar-interfaces.ts
  packages/toolbar/src/browser/toolbar-preference-contribution.ts
  packages/toolbar/src/browser/toolbar-preference-schema.ts
  packages/toolbar/src/browser/toolbar-storage-provider.ts
  packages/toolbar/src/browser/toolbar.tsx
  packages/toolbar/tsconfig.json
  tsconfig.json
Labels: toolbar

#10525 Update Themes
  package.json
  packages/monaco/data/monaco-themes/vscode/dark_defaults.json
  packages/monaco/data/monaco-themes/vscode/dark_plus.json
  packages/monaco/data/monaco-themes/vscode/dark_vs.json
  packages/monaco/data/monaco-themes/vscode/hc_black.json
  packages/monaco/data/monaco-themes/vscode/hc_black_defaults.json
  packages/monaco/data/monaco-themes/vscode/light_defaults.json
  packages/monaco/data/monaco-themes/vscode/light_plus.json
  packages/monaco/data/monaco-themes/vscode/light_vs.json
  packages/monaco/src/browser/textmate/monaco-theme-registry.ts
Labels: CQ Required, dependencies

#10798 changelog: update changelog for `v1.23.0`
  CHANGELOG.md
  packages/plugin-ext/src/main/browser/plugin-authentication-service.ts
Labels: documentation

#10801 Improve key binding rendering
  packages/core/src/browser/keybinding.ts
  packages/core/src/browser/keyboard/keyboard-layout-service.ts
  packages/keymaps/src/browser/keybindings-widget.tsx
Labels: keybindings

#10810 Use `OpenService` to handle preferences
  packages/preferences/src/browser/preference-frontend-module.ts
  packages/preferences/src/browser/preference-open-handler.ts
  packages/preferences/src/browser/views/components/preference-node-renderer.ts
  packages/preferences/src/browser/views/preference-widget.tsx
Labels: preferences
