Repository eclipse-theia/theia, pull requests merged in 2022-11, with the labels that each got.

#11821 docs: add `socket.io-parser` resolution
  doc/Migration.md
Labels: documentation, security

#11759 Add `task#runOptions` to API.
  CHANGELOG.md
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/tasks-main.ts
  packages/plugin-ext/src/plugin/type-converters.spec.ts
  packages/plugin-ext/src/plugin/type-converters.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
  packages/task/src/browser/task-configurations.ts
  packages/task/src/browser/task-service.ts
  packages/task/src/common/task-protocol.ts
Labels: tasks, vscode

#11823 plugin: update default api version to `1.55.2`
  CHANGELOG.md
  dev-packages/application-package/src/api.ts
Labels: plug-in system, vscode

#11762 Added unit tests for the functions in object.
  packages/core/src/common/objects.spec.ts
Labels: test

#11830 Fix package resolving failure in CLI
  dev-packages/application-package/package.json
  dev-packages/application-package/src/application-package.ts
  dev-packages/application-package/src/extension-package-collector.ts
  yarn.lock
Labels: quality, theia-cli

#11835 Fix some webpack warnings
  dev-packages/application-manager/src/generator/webpack-generator.ts
  packages/plugin-ext/src/main/browser/style/index.css
Labels: quality

#11751 Add support for lifecycleManagedByParent.
  packages/debug/src/browser/debug-session-manager.ts
  packages/debug/src/browser/debug-session.tsx
  packages/debug/src/common/debug-configuration.ts
  packages/plugin/src/theia.d.ts
Labels: vscode, debug

#11842 Fix: zh-cn localization
  packages/core/i18n/nls.zh-cn.json
Labels: localization

#11834 vscode: fix `separator` in quick-open
  packages/plugin-ext/src/plugin/quick-open.ts
Labels: monaco, vscode

#11798 vscode: add deprecated `withScmProgress`
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin/src/theia.d.ts
Labels: vscode, scm

#11818 Theia 3PP license check workflow improvement: retry upon failure, after a delay
  .github/workflows/license-check.yml
Labels: ci, dependencies

#11848 Remove reference to comparator's filtered report
  doc/Plugin-API.md
Labels: documentation

#11849 repo: perform `yarn upgrade`
  yarn.lock
Labels: security, dependencies

#11802 Add support explorer.decorations.colors preference
  packages/navigator/src/browser/abstract-navigator-tree-widget.ts
  packages/navigator/src/browser/navigator-preferences.ts
  packages/navigator/src/browser/navigator-widget.tsx
  packages/navigator/src/browser/open-editors-widget/navigator-open-editors-widget.tsx
Labels: preferences, navigator

#11857 Fix potential race condition when copying files and directories
  packages/filesystem/src/node/disk-file-system-provider.ts
Labels: filesystem

#11787 monaco: uplift to `1.72.3`
  examples/api-samples/package.json
  examples/api-tests/src/typescript.spec.js
  examples/playwright/src/theia-quick-command-palette.ts
  examples/playwright/src/theia-text-editor.ts
  packages/bulk-edit/package.json
  packages/console/package.json
  packages/core/src/browser/context-key-service.ts
  packages/core/src/browser/resource-context-key.ts
  packages/core/src/browser/shell/application-shell.ts
  packages/debug/package.json
  packages/debug/src/browser/disassembly-view/disassembly-view-instruction-renderer.ts
  packages/debug/src/browser/editor/debug-breakpoint-widget.tsx
  packages/debug/src/browser/editor/debug-editor-model.ts
  packages/debug/src/browser/editor/debug-inline-value-decorator.ts
  packages/editor/src/browser/editor-generated-preference-schema.ts
  packages/git/package.json
  packages/keymaps/package.json
  packages/monaco/package.json
  packages/monaco/src/browser/monaco-bulk-edit-service.ts
  packages/monaco/src/browser/monaco-context-key-service.ts
  packages/monaco/src/browser/monaco-gotoline-quick-access.ts
  packages/monaco/src/browser/monaco-gotosymbol-quick-access.ts
  packages/monaco/src/browser/monaco-menu.ts
  packages/monaco/src/browser/monaco-quick-input-service.ts
  packages/monaco/src/browser/monaco-workspace.ts
  packages/monaco/src/browser/style/index.css
  packages/output/package.json
  packages/plugin-ext-vscode/package.json
  packages/plugin-ext/package.json
  packages/plugin-ext/src/common/plugin-api-rpc-model.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/languages-main.ts
  packages/plugin-ext/src/main/browser/menus/plugin-menu-command-adapter.ts
  packages/plugin-ext/src/main/browser/text-editor-main.ts
  packages/plugin-ext/src/main/browser/theme-icon-override.ts
  packages/plugin-ext/src/plugin/languages.ts
  packages/plugin-ext/src/plugin/preference-registry.ts
  packages/plugin-ext/src/plugin/type-converters.ts
  packages/plugin-metrics/package.json
  packages/preferences/package.json
  packages/task/package.json
  packages/toolbar/package.json
  packages/variable-resolver/src/browser/common-variable-contribution.ts
  yarn.lock
Labels: monaco

#11859 ci: fix linting and adjust job order
  .github/workflows/ci-cd.yml
  packages/monaco/src/browser/monaco-context-key-service.ts
Labels: ci, linting

#11817 plugin-ext: cleanup `theia.d.ts` for `extensions`
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia-extra.d.ts
  packages/plugin/src/theia.d.ts
Labels: plug-in system, vscode

#11845 ci: cleanup github actions
  .github/workflows/ci-cd.yml
  .github/workflows/license-check.yml
  .github/workflows/playwright.yml
  .github/workflows/set-milestone-on-pr.yml
  .github/workflows/translation.yml
Labels: ci

#11856 Refined top level readme
  README.md
Labels: documentation

#11538 workspace: cleanup multiroot handling
  CHANGELOG.md
  packages/core/i18n/nls.cs.json
  packages/core/i18n/nls.de.json
  packages/core/i18n/nls.es.json
  packages/core/i18n/nls.fr.json
  packages/core/i18n/nls.hu.json
  packages/core/i18n/nls.it.json
  packages/core/i18n/nls.ja.json
  packages/core/i18n/nls.json
  packages/core/i18n/nls.pl.json
  packages/core/i18n/nls.pt-br.json
  packages/core/i18n/nls.pt-pt.json
  packages/core/i18n/nls.ru.json
  packages/core/i18n/nls.zh-cn.json
  packages/navigator/src/browser/navigator-contribution.ts
  packages/workspace/src/browser/quick-open-workspace.ts
  packages/workspace/src/browser/workspace-commands.ts
  packages/workspace/src/browser/workspace-frontend-contribution.spec.ts
  packages/workspace/src/browser/workspace-frontend-contribution.ts
  packages/workspace/src/browser/workspace-preferences.ts
  packages/workspace/src/browser/workspace-service.ts
Labels: workspace, multi-root

#11864 Remove circular dependency check
  dev-packages/application-manager/package.json
  dev-packages/application-manager/src/generator/webpack-generator.ts
  doc/Migration.md
  yarn.lock
Labels: theia-cli

#11767 Add full support for TerminalOptions.shellArgs
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/terminal-ext.ts
  packages/plugin/src/theia.d.ts
  packages/terminal/src/browser/base/terminal-widget.ts
  packages/terminal/src/common/shell-terminal-protocol.ts
  packages/terminal/src/node/shell-process.ts
Labels: OS/Windows, vscode

#11784 Upgrade vscode-textmate to ^7.0.3
  packages/monaco/package.json
  packages/monaco/src/browser/textmate/monaco-textmate-frontend-bindings.ts
  packages/monaco/src/browser/textmate/monaco-theme-registry.ts
  packages/monaco/src/browser/textmate/monaco-theme-types.ts
  packages/monaco/src/browser/textmate/textmate-tokenizer.ts
  packages/plugin-ext/package.json
  packages/plugin-ext/src/main/browser/plugin-contribution-handler.ts
  yarn.lock
Labels: monaco, dependencies

#11882 doc: add entry for VSCode API compatibility report
  README.md
Labels: documentation

#11877 repo: upgrade `yarn.lock`
  yarn.lock
Labels: security, dependencies

#11895 debug: fix expansion toggle styling
  packages/debug/src/browser/style/index.css
Labels: debug, ui/ux

#11906 nls: add localizations for preference validation
  packages/preferences/src/browser/views/components/preference-number-input.ts
Labels: preferences, localization

#11869 Generic hover service support
  packages/core/src/browser/frontend-application-module.ts
  packages/core/src/browser/hover-service.ts
  packages/core/src/browser/index.ts
  packages/core/src/browser/shell/sidebar-menu-widget.tsx
  packages/core/src/browser/shell/tab-bars.ts
  packages/core/src/browser/status-bar/index.ts
  packages/core/src/browser/status-bar/status-bar-hover-manager.ts
  packages/core/src/browser/status-bar/status-bar.tsx
  packages/core/src/browser/style/hover-service.css
  packages/core/src/browser/style/status-bar.css
  packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx
  packages/vsx-registry/src/browser/vsx-extension.tsx
Labels: ui/ux

#11914 Prioritize TreeView label provider
  packages/core/src/browser/icon-theme-service.ts
  packages/core/src/browser/label-provider.ts
  packages/plugin-ext/src/main/browser/view/plugin-tree-view-node-label-provider.ts
Labels: vscode

#11872 explorer: support `copy` for dnd
  packages/filesystem/src/browser/file-tree/file-tree-widget.tsx
Labels: navigator, dnd

#11860 ci: make plugin download sequential
  .github/workflows/ci-cd.yml
  .gitpod.yml
  CHANGELOG.md
  dev-packages/cli/src/download-plugins.ts
  dev-packages/cli/src/theia.ts
  devfile.yaml
  package.json
Labels: ci, theia-cli

#11810 Remove the multiplexer on window reload/close
  packages/core/src/electron-main/messaging/electron-messaging-contribution.ts
Labels: electron

#11794 fix: make on first tab cycle back to last tab
  packages/core/src/browser/shell/application-shell.ts
Labels: shell

#11918 docs: update changelog for `1.32.0`
  CHANGELOG.md
Labels: documentation

#11922 output: fix unique key error
  packages/output/src/browser/output-toolbar-contribution.tsx
Labels: output

#11910 Fix handling of submenu children of toolbars
  CHANGELOG.md
  examples/api-samples/src/browser/menu/sample-browser-menu-module.ts
  packages/core/src/browser/menu/browser-menu-plugin.ts
  packages/core/src/browser/shell/tab-bar-toolbar/tab-bar-toolbar.tsx
  packages/core/src/common/menu/composite-menu-node.ts
  packages/core/src/common/menu/menu-model-registry.ts
  packages/core/src/common/menu/menu-types.ts
  packages/plugin-ext/src/main/browser/comments/comment-thread-widget.tsx
  packages/scm/src/browser/scm-tree-widget.tsx
Labels: git, menus, builtins

#11808 Support for declaring extensions as peer dependencies
  dev-packages/application-package/src/extension-package-collector.ts
  dev-packages/application-package/src/npm-registry.ts
Labels: dependencies
