Repository eclipse-theia/theia, pull requests merged in 2022-10, with the labels that each got.

#11727 output: fix the selected channel name
  packages/output/src/browser/output-toolbar-contribution.tsx
Labels: output

#11733 vscode: Support `Terminal.state`
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/terminal-main.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/terminal-ext.ts
  packages/plugin/src/theia.d.ts
Labels: terminal, vscode

#11731 ci: update to use `ubuntu-latest` runners
  .github/workflows/ci-cd.yml
  .github/workflows/license-check.yml
  .github/workflows/playwright.yml
  .github/workflows/set-milestone-on-pr.yml
Labels: ci

#11734 docs: remove `theia-apps` references
  README.md
  doc/Publishing.md
Labels: documentation, docker

#11728 repo: upgrade `yarn.lock`
  packages/callhierarchy/src/browser/callhierarchy-tree/callhierarchy-tree.ts
  yarn.lock
Labels: dependencies

#11729 #10028 Support InlineValue feature
  CHANGELOG.md
  packages/debug/src/browser/editor/debug-inline-value-decorator.ts
  packages/plugin-ext/src/common/plugin-api-rpc-model.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/languages-main.ts
  packages/plugin-ext/src/plugin/languages.ts
  packages/plugin-ext/src/plugin/languages/inline-values.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/type-converters.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
Labels: vscode

#11552 terminal: Support VS Code Terminal Link Providers
  CHANGELOG.md
  packages/plugin-ext/src/common/plugin-api-rpc-model.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/terminal-main.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/terminal-ext.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
  packages/terminal/src/browser/terminal-file-link-provider.ts
  packages/terminal/src/browser/terminal-frontend-module.ts
  packages/terminal/src/browser/terminal-link-helpers.ts
  packages/terminal/src/browser/terminal-link-provider.ts
  packages/terminal/src/browser/terminal-linkmatcher-diff.ts
  packages/terminal/src/browser/terminal-linkmatcher.ts
  packages/terminal/src/browser/terminal-url-link-provider.ts
  packages/terminal/src/browser/terminal-widget-impl.ts
Labels: vscode, CQ Required

#11755 Improved HostedPluginSupport extensibility
  packages/plugin-ext/src/hosted/browser/hosted-plugin.ts
Labels: plug-in system, extensibility

#11741 Register VSCode items directly with corresponding internal menus
  CHANGELOG.md
  packages/core/src/common/menu/composite-menu-node.ts
  packages/plugin-ext/src/main/browser/menus/menus-contribution-handler.ts
  packages/plugin-ext/src/main/browser/menus/plugin-menu-command-adapter.ts
  packages/plugin-ext/src/main/browser/menus/vscode-theia-menu-mappings.ts
  packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx
Labels: vscode, menus

#11630 vscode: Support TerminalOptions.hideFromUser
  packages/plugin-ext/src/main/browser/terminal-main.ts
  packages/plugin/src/theia.d.ts
  packages/terminal/src/browser/base/terminal-widget.ts
  packages/terminal/src/browser/terminal-quick-open-service.ts
  packages/terminal/src/browser/terminal-widget-impl.ts
Labels: terminal, vscode

#11754 make `@theia/ffmpeg` lazy
  dev-packages/application-manager/src/application-package-manager.ts
  dev-packages/cli/src/theia.ts
  dev-packages/ffmpeg/src/ffmpeg.ts
Labels: bug, ffmpeg

#11770 [CI] Fix license check for non-committers
  scripts/check_3pp_licenses.js
Labels: ci

#11761 Move breaking change to correct version
  CHANGELOG.md
Labels: documentation

#11736 vscode: add support for inlay hints
  packages/plugin-ext/src/common/cache.ts
  packages/plugin-ext/src/common/plugin-api-rpc-model.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/languages-main.ts
  packages/plugin-ext/src/plugin/custom-editors.ts
  packages/plugin-ext/src/plugin/languages.ts
  packages/plugin-ext/src/plugin/languages/inlay-hints.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/type-converters.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
Labels: monaco, vscode, CQ Required

#11764 Check whether editor commands are declared in package.json
  packages/plugin-ext/src/plugin/plugin-context.ts
Labels: vscode

#11694 Support vscode TypeHierarchy API (references-view)
  CHANGELOG.md
  packages/plugin-ext-vscode/package.json
  packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts
  packages/plugin-ext-vscode/tsconfig.json
  packages/plugin-ext/package.json
  packages/plugin-ext/src/common/plugin-api-rpc-model.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/callhierarchy/callhierarchy-type-converters.ts
  packages/plugin-ext/src/main/browser/hierarchy/hierarchy-types-converters.ts
  packages/plugin-ext/src/main/browser/languages-main.ts
  packages/plugin-ext/src/plugin/known-commands.ts
  packages/plugin-ext/src/plugin/languages.ts
  packages/plugin-ext/src/plugin/languages/call-hierarchy.ts
  packages/plugin-ext/src/plugin/languages/type-hierarchy.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/type-converters.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin-ext/tsconfig.json
  packages/plugin/src/theia.d.ts
  packages/typehierarchy/src/browser/index.ts
  packages/typehierarchy/src/browser/typehierarchy-contribution.ts
  packages/typehierarchy/src/browser/typehierarchy-frontend-module.ts
  packages/typehierarchy/src/browser/typehierarchy-service.ts
  packages/typehierarchy/src/browser/typehierarchy.ts
Labels: vscode, languages

#11717 Stub vscode 'Tests' API
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/stubs/tests-api.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
Labels: plug-in system, vscode, stub

#11805 git: fix `unstage all`
  packages/git/src/browser/git-scm-provider.ts
Labels: git

#11804 docs: update changelog for `1.31.0`
  CHANGELOG.md
  packages/core/src/common/message-rpc/rpc-message-encoder.spec.ts
  packages/plugin-ext/src/plugin/preference-registry.spec.ts
Labels: documentation

#11806 git: fix unstage all and add unit test
  packages/git/src/browser/git-scm-provider.spec.ts
Labels: git

#11814 docs: update `1.31.0` changelog for `unstage all`
  CHANGELOG.md
Labels: git, documentation

#11819 deps: upgrade `socket.io`
  packages/core/package.json
  yarn.lock
Labels: security, dependencies
