Repository eclipse-theia/theia, pull requests merged in 2023-02, with the labels that each got.

#12133 Update `trash` dependency to 7.2.0
  packages/filesystem/package.json
  yarn.lock
Labels: dependencies

#12109 Tab API implementation
  packages/core/src/browser/shell/application-shell.ts
  packages/plugin-ext/package.json
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/main-context.ts
  packages/plugin-ext/src/main/browser/tabs/tabs-main.ts
  packages/plugin-ext/src/plugin/tabs.ts
  packages/plugin-ext/tsconfig.json
  packages/plugin/src/theia.d.ts
Labels: vscode

#12151 [CI] [license check] Always specify project
  scripts/check_3pp_licenses.js
Labels: ci

#12145 Implement workbench.editor.revealIfOpen preference
  packages/core/src/browser/core-preferences.ts
  packages/editor/src/browser/editor-manager.ts
Labels: preferences, editor

#12150 Remove script for downloading debug adapters
  package.json
  packages/debug/bin/download-adapters.js
  packages/debug/package.json
  yarn.lock
Labels: dependencies

#12152 vscode: bump default api to `1.68.1`
  dev-packages/application-package/src/api.ts
Labels: vscode

#12134 Align terminal command ids with VS Code. Fixes #12084
  packages/plugin-ext/src/plugin/dialogs.ts
  packages/plugin-ext/src/plugin/known-commands.ts
Labels: terminal, vscode

#12141 playwright: upgrade dependency
  examples/playwright/package.json
  yarn.lock
Labels: dependencies, playwright

#12158 FIX 12154: add margin between input and text
  packages/workspace/src/browser/workspace-input-dialog.ts
Labels: dialogs

#12147 Close duplicate editors on same tabbar
  packages/editor-preview/src/browser/editor-preview-widget.ts
  packages/editor/src/browser/editor-widget.ts
Labels: shell

#12136 Allow plugins to access language overrides with bracket syntax
  packages/plugin-ext/src/plugin/preference-registry.spec.ts
  packages/plugin-ext/src/plugin/preference-registry.ts
Labels: preferences, vscode

#12159 Ensure uniqueness of roots
  packages/workspace/src/browser/workspace-service.ts
Labels: workspace

#12167 Automatically generate plugin activation events
  packages/plugin-ext/src/common/plugin-protocol.ts
  packages/plugin-ext/src/hosted/node/plugin-activation-events.ts
  packages/plugin-ext/src/hosted/node/plugin-manifest-loader.ts
  packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts
Labels: plug-in system

#12181 repo: yarn upgrade
  package.json
  packages/monaco/src/browser/textmate/monaco-textmate-frontend-bindings.ts
  packages/monaco/src/browser/textmate/textmate-tokenizer.ts
  yarn.lock
Labels: security, dependencies

#12125 Support `DocumentDropEditProvider` (#12025)
  packages/filesystem/src/browser/file-upload-service.ts
  packages/filesystem/src/node/node-file-upload-service.ts
  packages/plugin-ext/src/common/plugin-api-rpc-model.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/data-transfer/data-transfer-type-converters.ts
  packages/plugin-ext/src/main/browser/languages-main.ts
  packages/plugin-ext/src/plugin/file-system-ext-impl.ts
  packages/plugin-ext/src/plugin/languages.ts
  packages/plugin-ext/src/plugin/languages/document-drop-edit.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/type-converters.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
Labels: vscode

#12179 Option to toggle hidden folders/files in browser file dialog
  packages/filesystem/src/browser/file-dialog/file-dialog-hidden-files-renderer.tsx
  packages/filesystem/src/browser/file-dialog/file-dialog-module.ts
  packages/filesystem/src/browser/file-dialog/file-dialog-tree.ts
  packages/filesystem/src/browser/file-dialog/file-dialog.ts
  packages/filesystem/src/browser/style/file-dialog.css
Labels: file dialog

#12033 Added localization for debug level selector
  packages/core/src/common/severity.ts
  packages/debug/src/browser/console/debug-console-contribution.tsx
Labels: localization

#12199 Correctly pass selected workspace root to terminal profile
  packages/terminal/src/browser/shell-terminal-profile.ts
  packages/terminal/src/browser/terminal-frontend-contribution.ts
Labels: terminal

#12191 Handle the case where no default terminal profile is set no startup
  packages/terminal/src/browser/terminal-frontend-contribution.ts
Labels: terminal

#12190 Properly return instruction breakpoints in DebugSession
  packages/debug/src/browser/debug-session.tsx
Labels: debug, disassembly

#12067 Toolbars: ToolbarItem.when field is evaluated and respected
  packages/core/src/browser/shell/tab-bar-toolbar/tab-bar-toolbar.tsx
  packages/toolbar/src/browser/toolbar-preference-schema.ts
  packages/toolbar/src/browser/toolbar.tsx
Labels: toolbar

#12138 Fix #12137: Webview that not implements a WebviewPanelSerializer should not restore automatically after reconnecting.
  packages/plugin-ext/src/hosted/browser/hosted-plugin.ts
Labels: webviews

#12201 Fix tab API stub and indentation
  packages/plugin/src/theia.d.ts
Labels: vscode

#12094 repo: update builtins to `1.64.2`, `1.66.2`
  package.json
Labels: builtins

#12077 style: sidepanel styling - hidden title quick fix
  packages/core/src/browser/style/sidepanel.css
Labels: ui/ux

#12117 Fix browser test suite
  dev-packages/cli/src/run-test.ts
  dev-packages/cli/src/test-page.ts
  dev-packages/cli/src/theia.ts
  examples/api-tests/src/browser-utils.spec.js
  examples/api-tests/src/find-replace.spec.js
  examples/api-tests/src/keybindings.spec.js
  examples/api-tests/src/launch-preferences.spec.js
  examples/api-tests/src/saveable.spec.js
  examples/api-tests/src/typescript.spec.js
Labels: ci, test

#12205 Update nls.metadata.json for vscode API 1.70.2
  packages/core/src/browser/common-frontend-contribution.ts
  packages/core/src/browser/core-preferences.ts
  packages/core/src/browser/i18n/language-quick-pick-service.ts
  packages/core/src/browser/tree/search-box.ts
  packages/core/src/common/i18n/nls.metadata.json
  packages/editor/src/browser/editor-generated-preference-schema.ts
  packages/filesystem/src/browser/filesystem-preferences.ts
  packages/search-in-workspace/src/browser/search-in-workspace-preferences.ts
  packages/terminal/src/browser/terminal-preferences.ts
Labels: localization

#12210 Do not (re)store state of Open Editors
  packages/navigator/src/browser/open-editors-widget/navigator-open-editors-widget.tsx
Labels: open-editors

#12183 Fire breakpoint events only if breakpoint metadata changes
  packages/debug/package.json
  packages/debug/src/browser/breakpoint/breakpoint-manager.ts
  packages/debug/src/browser/editor/debug-editor-model.ts
Labels: debug

#12182 webview: add support for `activeWebviewPanelId`
  packages/plugin-ext/src/main/browser/plugin-ext-frontend-module.ts
  packages/plugin-ext/src/main/browser/webview/webview-context-keys.ts
Labels: vscode, webviews

#12212 repo: pin `ts` plugins
  package.json
Labels: typescript, builtins

#12209 [browser tests] [typescript] disable files.refactoring.autoSave
  examples/api-tests/src/typescript.spec.js
Labels: ci

#12213 Revert "preferences: fix `PreferenceProvider.merge` method (#12126)"
  examples/api-tests/src/launch-preferences.spec.js
  packages/core/src/browser/preferences/preference-provider.spec.ts
  packages/core/src/browser/preferences/preference-provider.ts
Labels: preferences

#12216 docs: update changelog for 1.35.0
  CHANGELOG.md
Labels: documentation

#12221 Fix recursive webview-view title setter
  packages/plugin-ext/src/plugin/webview-views.ts
Labels: webviews

#12222 [browser tests] update Puppeteer
  dev-packages/cli/package.json
  dev-packages/cli/src/run-test.ts
  dev-packages/cli/src/test-page.ts
  dev-packages/cli/src/theia.ts
  package.json
  yarn.lock
Labels: ci, playwright
