Repository eclipse-theia/theia, pull requests merged in 2023-11, with the labels that each got.

#13054 fix: omit proxy path prefix from socket.io base path
  packages/core/src/browser/messaging/ws-connection-provider.ts
Labels: websocket

#13014 Support VS Code Default Language Icons
  packages/core/src/browser/frontend-application-module.ts
  packages/core/src/browser/icon-theme-contribution.ts
  packages/core/src/browser/icon-theme-service.ts
  packages/core/src/browser/language-icon-provider.ts
  packages/core/src/browser/language-service.ts
  packages/monaco/src/browser/monaco-languages.ts
  packages/plugin-ext/src/common/plugin-protocol.ts
  packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts
  packages/plugin-ext/src/main/browser/plugin-contribution-handler.ts
  packages/plugin-ext/src/main/browser/plugin-icon-theme-service.ts
  packages/plugin-ext/src/main/browser/plugin-shared-style.ts
Labels: theming

#13071 Fix SiW result line styling
  packages/search-in-workspace/src/browser/styles/index.css
Labels: search in workspace, ui/ux

#13017 Correctly localize debug schema attributes
  packages/debug/src/node/vscode/vscode-debug-adapter-contribution.ts
  packages/plugin-ext/src/common/plugin-protocol.ts
  packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts
  packages/plugin-ext/src/main/browser/debug/plugin-debug-service.ts
Labels: debug, localization

#13078 Improve default translation using preferred keys
  packages/core/src/common/nls.ts
Labels: localization

#13111 license: update baseline
  dependency-check-baseline.json
Labels: dependencies

#12990 repo: perform `yarn upgrade`
  examples/api-samples/src/electron-main/update/sample-updater-impl.ts
  packages/core/src/electron-main/electron-main-application.ts
  packages/filesystem/src/node/nsfw-watcher/nsfw-filesystem-service.ts
  packages/plugin-ext/src/plugin/status-bar/status-bar-item.ts
  yarn.lock
Labels: quality, security, dependencies

#13075 fix(task): Align task group validation with VS Code
  CHANGELOG.md
  packages/task/src/browser/task-schema-updater.ts
Labels: tasks

#13112 Add option to copy `trash` dependency to bundle
  dev-packages/application-manager/src/generator/webpack-generator.ts
  dev-packages/native-webpack-plugin/src/native-webpack-plugin.ts
Labels: filesystem, bundle

#13122 doc/developing.md: fixed link to '../dev-packages/private-ext-scripts/README.md'
  doc/Developing.md
Labels: documentation

#13119 Update nls metadata for vscode API 1.83
  packages/core/src/common/i18n/nls.metadata.json
  packages/core/src/electron-browser/window/electron-window-preferences.ts
  packages/editor/src/browser/editor-generated-preference-schema.ts
Labels: localization

#13127 ext-scripts: fixed and improved ext-scripts/README.md
  dev-packages/private-ext-scripts/README.md
Labels: documentation

#13130 ci: pin python version for the translations
  .github/workflows/translation.yml
Labels: ci, localization
