Repository eclipse-theia/theia, pull requests merged in 2023-05, with the labels that each got.

#12411 Add "open tabs" drop down
  CHANGELOG.md
  examples/playwright/src/tests/theia-terminal-view.test.ts
  examples/playwright/src/tests/theia-text-editor.test.ts
  examples/playwright/src/theia-view.ts
  packages/core/src/browser/shell/tab-bars.ts
  packages/core/src/browser/style/tabs.css
  packages/core/src/browser/widgets/select-component.tsx
Labels: ui/ux

#12491 move preload bits under Electron only
  dev-packages/application-manager/src/generator/frontend-generator.ts
  dev-packages/application-manager/src/generator/webpack-generator.ts
Labels: electron

#12400 fixed #12392. Tab indices now updated
  packages/plugin-ext/src/main/browser/tabs/tabs-main.ts
Labels: vscode

#12331 Search-In-Workspace: Add multiselect functionality
  packages/search-in-workspace/src/browser/search-in-workspace-frontend-contribution.ts
  packages/search-in-workspace/src/browser/search-in-workspace-frontend-module.ts
  packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx
  packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx
Labels: search in workspace

#12453 [vscode] support TelemetryLogger
  packages/core/src/common/index.ts
  packages/core/src/common/objects.ts
  packages/core/src/common/telemetry.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/plugin/env.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/telemetry-ext.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
Labels: vscode, CQ Required

#12504 Clean up Readme.md
  README.md
Labels: documentation

#12509 Fixed typo in readme (#12505)
  README.md
Labels: documentation

#12506 editor: add confirmation prompt when executing clear editor history
  packages/editor/src/browser/editor-navigation-contribution.ts
Labels: editor, ui/ux

#12508 [vscode] Stub for proposed API: EditSessionIdentityProvider
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/workspace.ts
  packages/plugin/src/theia-proposed.d.ts
Labels: vscode, builtins

#12512 Stub for proposed API: DocumentPaste
  packages/plugin-ext/src/plugin/languages.ts
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia-proposed.d.ts
Labels: vscode, builtins

#12510 core: add confirmation prompt when executing clear command history
  packages/core/src/browser/quick-input/quick-command-frontend-contribution.ts
Labels: core, ui/ux

#12507 Fix missing options related to 'Tasks'
  packages/task/src/browser/provided-task-configurations.ts
  packages/task/src/browser/quick-open-task.ts
Labels: tasks

#12482 Associate root folder to dynamic debug configurations
  CHANGELOG.md
  packages/debug/src/browser/debug-configuration-manager.ts
  packages/debug/src/browser/debug-prefix-configuration.ts
  packages/debug/src/browser/view/debug-configuration-select.tsx
  packages/debug/src/common/debug-service.ts
  packages/debug/src/node/debug-service-impl.ts
  packages/plugin-ext/src/main/browser/debug/plugin-debug-service.ts
Labels: plug-in system, debug, python

#12527 docs: add `msgpackr` resolution note
  doc/Migration.md
Labels: documentation

#12317 fix monaco suggest list highlight color overlap in light theme
  packages/monaco/src/browser/style/index.css
Labels: theming, monaco

#12489 Fix TreeView.reveal() behavior.
  packages/plugin-ext/src/plugin/tree/tree-views.ts
Labels: tree, vscode

#12539 Stub for proposed API: ExternalUriOpener
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
  packages/plugin/src/theia.proposed.externalUriOpener.d.ts
Labels: vscode, builtins, stub

#12457 Notifications: Toaster Container did not close when empty
  packages/messages/src/browser/notifications-manager.ts
Labels: monaco

#12113 fixes #12112 Removing exited thread from threads
  packages/debug/src/browser/debug-session.tsx
Labels: debug

#12535 vscode: add `ProfileContentHandler` API stubbing
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin/src/theia-proposed.d.ts
Labels: vscode, builtins

#12532 vscode: add `TerminalQuickFixProvider` API stubbing
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/terminal-ext.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia-proposed.d.ts
Labels: vscode, builtins

#12545 [ci][3PP License Check] Detect when dash-licenses exits with an internal error
  scripts/check_3pp_licenses.js
Labels: ci

#12514 Show "Collapse All" command in tree view toolbar.
  packages/core/src/browser/view-container.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/plugin-ext-frontend-module.ts
  packages/plugin-ext/src/main/browser/plugin-frontend-contribution.ts
  packages/plugin-ext/src/main/browser/view/plugin-view-widget.ts
  packages/plugin-ext/src/main/browser/view/tree-view-widget.tsx
  packages/plugin-ext/src/main/browser/view/tree-views-main.ts
  packages/plugin-ext/src/plugin/tree/tree-views.ts
Labels: tree, vscode

#12516 [chore][vscode] update default service API to 1.77.0
  dev-packages/application-package/src/api.ts
Labels: vscode, builtins

#12408 Improve problem view performance
  packages/markers/src/browser/problem/problem-composite-tree-node.spec.ts
  packages/markers/src/browser/problem/problem-composite-tree-node.ts
  packages/markers/src/browser/problem/problem-decorations-provider.ts
  packages/markers/src/browser/problem/problem-tree-model.ts
  packages/monaco/src/browser/monaco-diagnostic-collection.ts
  packages/monaco/src/browser/monaco-languages.ts
  packages/monaco/src/browser/monaco-marker-collection.ts
Labels: problems

#12480 Fixed #12475: Debug toobar not showing current launch configuration on startup
  packages/debug/src/browser/view/debug-configuration-select.tsx
Labels: debug, ui/ux

#12555 Update nls metadata file for vscode version 1.77.0
  examples/playwright/src/tests/theia-main-menu.test.ts
  packages/core/src/browser/common-frontend-contribution.ts
  packages/core/src/browser/core-preferences.ts
  packages/core/src/common/i18n/nls.metadata.json
  packages/core/src/common/severity.ts
  packages/debug/src/browser/debug-preferences.ts
  packages/editor-preview/src/browser/editor-preview-preferences.ts
  packages/editor/src/browser/editor-generated-preference-schema.ts
  packages/filesystem/src/browser/filesystem-preferences.ts
  packages/navigator/src/browser/navigator-contribution.ts
  packages/navigator/src/browser/navigator-preferences.ts
  packages/output/src/browser/output-contribution.ts
  packages/terminal/src/browser/terminal-preferences.ts
  packages/workspace/src/browser/workspace-commands.ts
Labels: localization

#12046 focus out possible again for debug configuration
  packages/debug/src/browser/debug-configuration-manager.ts
  packages/debug/src/browser/view/debug-configuration-select.tsx
Labels: debug

#12448 Themes: add High Contrast Dark theme missing tab markers
  packages/core/src/browser/common-styling-participants.ts
Labels: theming, ui/ux

#12544 fix: handle exception in WorkspaceDeleteHandler
  packages/workspace/src/browser/workspace-delete-handler.ts
Labels: quality, workspace

#12562 Remove pinned version markdown-language-features
  package.json
Labels: vscode, builtins

#12564 docs: update `changelog` for `1.38.0`
  CHANGELOG.md
  packages/core/src/browser/view-container.ts
Labels: documentation

#12576 Use builtin-extension-pack v1.77.0
  package.json
Labels: plug-in system, builtins

#12569 12568 Localized debug session status
  packages/debug/src/browser/debug-session.tsx
Labels: localization

#12571 12570 Localized quick file open labels
  packages/file-search/src/browser/quick-file-open.ts
Labels: localization
