Repository eclipse-theia/theia, pull requests merged in 2023-09, with the labels that each got.

#12832 Fix Inline breakpoint appears when deleting the last line code [#10874]
  packages/debug/src/browser/editor/debug-editor-model.ts
Labels: debug

#12590 Add inversify lifecycle to frontend preload script
  dev-packages/application-manager/src/generator/abstract-generator.ts
  dev-packages/application-manager/src/generator/backend-generator.ts
  dev-packages/application-manager/src/generator/frontend-generator.ts
  dev-packages/application-package/src/application-package.ts
  dev-packages/application-package/src/extension-package.ts
  packages/core/package.json
  packages/core/src/browser/preload/i18n-preload-contribution.ts
  packages/core/src/browser/preload/os-preload-contribution.ts
  packages/core/src/browser/preload/preload-module.ts
  packages/core/src/browser/preload/preloader.ts
  packages/core/src/browser/preload/theme-preload-contribution.ts
  packages/core/src/browser/preloader.ts
  packages/core/src/common/i18n/localization-server.ts
  packages/core/src/common/os.ts
  packages/core/src/node/backend-application-module.ts
  packages/core/src/node/i18n/i18n-backend-module.ts
  packages/core/src/node/i18n/localization-server.ts
  packages/core/src/node/os-backend-provider.ts
  packages/plugin-ext/src/main/node/plugin-ext-backend-module.ts
  packages/plugin-ext/src/main/node/plugin-localization-server.ts
Labels: quality, extensibility

#12830 Retire `context` keyword from keybindings
  packages/console/src/browser/console-contribution.ts
  packages/console/src/browser/console-frontend-module.ts
  packages/console/src/browser/console-keybinding-contexts.ts
  packages/console/src/browser/console-widget.ts
  packages/debug/src/browser/debug-frontend-application-contribution.ts
  packages/debug/src/browser/debug-frontend-module.ts
  packages/debug/src/browser/debug-keybinding-contexts.ts
  packages/debug/src/browser/editor/debug-breakpoint-widget.tsx
  packages/editor/src/browser/editor-frontend-module.ts
  packages/editor/src/browser/editor-keybinding-contexts.ts
  packages/editor/src/browser/index.ts
  packages/git/src/browser/blame/blame-contribution.ts
  packages/git/src/browser/blame/blame-module.ts
  packages/messages/src/browser/messages-frontend-module.ts
  packages/messages/src/browser/notifications-contribution.ts
  packages/messages/src/browser/notifications-manager.ts
  packages/monaco/src/browser/monaco-frontend-module.ts
  packages/monaco/src/browser/monaco-keybinding-contexts.ts
  packages/navigator/src/browser/navigator-contribution.ts
  packages/navigator/src/browser/navigator-frontend-module.ts
  packages/navigator/src/browser/navigator-keybinding-context.ts
  packages/terminal/src/browser/terminal-frontend-contribution.ts
  packages/terminal/src/browser/terminal-frontend-module.ts
  packages/terminal/src/browser/terminal-keybinding-contexts.ts
Labels: keybindings, quality

#12858 vsx-registry: add hint to fetching extensions error
  CHANGELOG.md
  packages/vsx-registry/src/browser/vsx-extensions-widget.tsx
Labels: vsx-registry

#12889 Keybinding: Error Message Localization
  packages/core/src/common/keys.ts
Labels: localization

#12868 Add support for multiline searches
  packages/search-in-workspace/package.json
  packages/search-in-workspace/src/browser/components/search-in-workspace-textarea.tsx
  packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx
  packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx
  packages/search-in-workspace/src/browser/styles/index.css
  packages/search-in-workspace/src/common/search-in-workspace-interface.ts
  packages/search-in-workspace/src/node/ripgrep-search-in-workspace-server.ts
Labels: search in workspace

#12566 fix: propagate log-config changes
  CHANGELOG.md
  packages/core/src/common/logger-protocol.ts
  packages/core/src/common/logger-watcher.ts
  packages/core/src/common/logger.ts
  packages/core/src/node/console-logger-server.ts
  packages/core/src/node/logger-backend-module.ts
Labels: logging

#12944 [vscode] Stub TestController invalidateTestResults
  CHANGELOG.md
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/stubs/tests-api.ts
  packages/plugin/src/theia.d.ts
Labels: vscode

#12945 vscode support iconPath in QuickPickItem
  CHANGELOG.md
  packages/core/src/common/quick-pick-service.ts
  packages/monaco/src/browser/monaco-quick-input-service.ts
  packages/plugin-ext/src/plugin/quick-open.ts
  packages/plugin-ext/src/plugin/type-converters.ts
  packages/plugin/src/theia.d.ts
Labels: vscode, quick-open

#12936 Improve frontend startup performance
  CHANGELOG.md
  packages/core/src/browser/common-frontend-contribution.ts
  packages/debug/src/browser/debug-frontend-application-contribution.ts
  packages/editor/src/browser/editor-navigation-contribution.ts
  packages/terminal/src/browser/terminal-frontend-contribution.ts
Labels: performance

#12950 fix: restore src-gen frontend production behavior
  CHANGELOG.md
  dev-packages/application-manager/src/generator/frontend-generator.ts
Labels: theia-cli

#12951 Update nls metadata file for API version 1.81.0
  examples/playwright/src/tests/theia-explorer-view.test.ts
  packages/core/src/common/i18n/nls.metadata.json
  packages/debug/src/browser/editor/debug-breakpoint-widget.tsx
  packages/getting-started/src/browser/getting-started-preferences.ts
  packages/terminal/src/browser/terminal-frontend-contribution.ts
Labels: localization

#12923 dialogs - Allow multiple selection on Open...
  CHANGELOG.md
  packages/workspace/src/browser/workspace-frontend-contribution.ts
Labels: file dialog

#12955 docs: update changelog for 1.42.0
  CHANGELOG.md
  packages/notebook/src/browser/service/notebook-kernel-quick-pick-service.ts
  packages/notebook/src/browser/view/notebook-markdown-cell-view.tsx
Labels: documentation
