Repository eclipse-theia/theia, pull requests merged in 2023-10, with the labels that each got.

#12841 Fix symlinks should be resolved when initializing plugins
  packages/plugin-ext/src/hosted/node/plugin-reader.ts
Labels: plug-in system

#12963 Update `vscode-textmate` dependency
  packages/monaco/package.json
  packages/monaco/src/browser/textmate/textmate-tokenizer.ts
  packages/plugin-ext/package.json
  yarn.lock
Labels: monaco, dependencies

#12958 deps: upgrade `chai`
  dev-packages/cli/package.json
  package.json
  yarn.lock
Labels: security, dependencies

#12803 core: refactor `manage` sidebar menu
  CHANGELOG.md
  packages/core/src/browser/common-frontend-contribution.ts
  packages/core/src/browser/quick-input/quick-command-frontend-contribution.ts
  packages/core/src/common/menu/menu-types.ts
  packages/keymaps/src/browser/keymaps-frontend-contribution.ts
  packages/preferences/src/browser/preferences-contribution.ts
  packages/task/src/browser/task-frontend-contribution.ts
  packages/vsx-registry/src/browser/vsx-extensions-contribution.ts
Labels: ui/ux

#12976 Fix URL path for output renderer scripts
  packages/plugin-ext/src/main/browser/notebooks/renderers/output-webview-internal.ts
  packages/plugin-ext/src/main/browser/plugin-contribution-handler.ts
Labels: notebook

#12913 Implement search.quickOpen.includeHistory preference
  packages/file-search/src/browser/quick-file-open.ts
  packages/search-in-workspace/src/browser/search-in-workspace-preferences.ts
Labels: preferences, file search

#12984 Implement EnvironmentVariableMutatorOptions API.
  packages/plugin-ext/src/plugin/terminal-ext.ts
  packages/plugin/src/theia.d.ts
  packages/terminal/src/common/base-terminal-protocol.ts
  packages/terminal/src/node/base-terminal-server.ts
Labels: vscode

#12910 Notebook API post review improvements
  packages/core/src/browser/saveable.ts
  packages/core/src/common/uri.ts
  packages/monaco/src/browser/monaco-languages.ts
  packages/monaco/src/browser/simple-monaco-editor.ts
  packages/notebook/src/browser/contributions/notebook-cell-actions-contribution.ts
  packages/notebook/src/browser/contributions/notebook-context-keys.ts
  packages/notebook/src/browser/index.ts
  packages/notebook/src/browser/notebook-cell-resource-resolver.ts
  packages/notebook/src/browser/notebook-editor-widget-factory.ts
  packages/notebook/src/browser/notebook-editor-widget.tsx
  packages/notebook/src/browser/notebook-frontend-module.ts
  packages/notebook/src/browser/notebook-open-handler.ts
  packages/notebook/src/browser/notebook-renderer-registry.ts
  packages/notebook/src/browser/notebook-type-registry.ts
  packages/notebook/src/browser/renderers/cell-output-webview.ts
  packages/notebook/src/browser/service/notebook-cell-context-manager.ts
  packages/notebook/src/browser/service/notebook-editor-widget-service.ts
  packages/notebook/src/browser/service/notebook-execution-service.ts
  packages/notebook/src/browser/service/notebook-execution-state-service.ts
  packages/notebook/src/browser/service/notebook-kernel-quick-pick-service.ts
  packages/notebook/src/browser/service/notebook-kernel-service.ts
  packages/notebook/src/browser/service/notebook-model-resolver-service.ts
  packages/notebook/src/browser/service/notebook-renderer-messaging-service.ts
  packages/notebook/src/browser/service/notebook-service.ts
  packages/notebook/src/browser/view-model/notebook-cell-model.ts
  packages/notebook/src/browser/view-model/notebook-model.ts
  packages/notebook/src/browser/view/notebook-cell-editor.tsx
  packages/notebook/src/common/notebook-common.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/hosted/browser/hosted-plugin.ts
  packages/plugin-ext/src/main/browser/notebooks/notebook-documents-and-editors-main.ts
  packages/plugin-ext/src/main/browser/notebooks/notebook-documents-main.ts
  packages/plugin-ext/src/main/browser/notebooks/notebook-dto.ts
  packages/plugin-ext/src/main/browser/notebooks/notebook-kernels-main.ts
  packages/plugin-ext/src/main/browser/notebooks/notebook-renderers-main.ts
  packages/plugin-ext/src/main/browser/notebooks/notebooks-main.ts
  packages/plugin-ext/src/plugin/notebook/notebooks.ts
Labels: notebook

#12791 keybindings: add context menu to keyboard shortcuts
  packages/core/src/common/keybinding.ts
  packages/keymaps/src/browser/keybindings-widget.tsx
  packages/keymaps/src/browser/keymaps-frontend-contribution.ts
  packages/keymaps/src/browser/keymaps-service.ts
  packages/keymaps/src/browser/style/index.css
Labels: keybindings

#13023 outputs now updating correctly when output items are updated.
  packages/notebook/src/browser/service/notebook-execution-state-service.ts
  packages/notebook/src/browser/view-model/notebook-cell-model.ts
  packages/notebook/src/browser/view-model/notebook-cell-output-model.ts
  packages/notebook/src/browser/view-model/notebook-model.ts
  packages/notebook/src/common/notebook-common.ts
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/notebooks/renderers/cell-output-webview.tsx
  packages/plugin-ext/src/main/browser/notebooks/renderers/output-webview-internal.ts
  packages/plugin-ext/src/plugin/notebook/notebook-kernels.ts
  packages/plugin-ext/src/plugin/type-converters.ts
Labels: notebook

#12975 fix: delete gen-webpack.node.config.js with `theia clean` command
  dev-packages/application-manager/src/application-package-manager.ts
Labels: theia-cli

#12902 Fix backend webpack output and watching
  dev-packages/application-manager/src/generator/webpack-generator.ts
  dev-packages/native-webpack-plugin/package.json
  dev-packages/native-webpack-plugin/src/native-webpack-plugin.ts
Labels: bundle

#12993 Fix localization import order
  CHANGELOG.md
  packages/core/src/browser/color-application-contribution.ts
  packages/core/src/browser/common-frontend-contribution.ts
  packages/core/src/browser/connection-status-service.ts
  packages/core/src/browser/dialogs.ts
  packages/core/src/browser/frontend-application-contribution.ts
  packages/core/src/browser/frontend-application-module.ts
  packages/core/src/browser/frontend-application.ts
  packages/core/src/browser/icon-theme-contribution.ts
  packages/core/src/browser/index.ts
  packages/core/src/browser/json-schema-store.ts
  packages/core/src/browser/label-provider.ts
  packages/core/src/browser/logger-frontend-module.ts
  packages/core/src/browser/menu/browser-menu-module.ts
  packages/core/src/browser/menu/browser-menu-plugin.ts
  packages/core/src/browser/quick-input/quick-input-frontend-contribution.ts
  packages/core/src/browser/shell/application-shell-mouse-tracker.ts
  packages/core/src/browser/shell/tab-bar-decorator.ts
  packages/core/src/browser/shell/tab-bar-toolbar/tab-bar-toolbar-registry.ts
  packages/core/src/browser/styling-service.ts
  packages/core/src/browser/window/browser-window-module.ts
  packages/core/src/browser/window/default-window-service.spec.ts
  packages/core/src/browser/window/default-window-service.ts
  packages/core/src/browser/window/window-title-updater.ts
  packages/core/src/electron-browser/messaging/electron-messaging-frontend-module.ts
  packages/core/src/electron-browser/messaging/electron-ws-connection-provider.ts
  packages/core/src/electron-browser/window/electron-window-module.ts
  packages/debug/src/browser/editor/debug-inline-value-decorator.ts
  packages/editor/src/browser/editor-navigation-contribution.ts
  packages/mini-browser/src/browser/mini-browser-frontend-module.ts
  packages/mini-browser/src/browser/mini-browser-open-handler.ts
  packages/monaco/package.json
  packages/monaco/src/browser/monaco-frontend-application-contribution.ts
  packages/monaco/tsconfig.json
  packages/outline-view/src/browser/outline-view-contribution.ts
  packages/vsx-registry/src/browser/vsx-extensions-contribution.ts
  packages/workspace/package.json
  packages/workspace/src/browser/workspace-frontend-contribution.ts
Labels: localization

#12912 vscode: support icons contribution point
  packages/core/src/browser/icon-registry.ts
  packages/monaco/src/browser/monaco-frontend-module.ts
  packages/monaco/src/browser/monaco-icon-registry.ts
  packages/plugin-ext/src/common/plugin-protocol.ts
  packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts
  packages/plugin-ext/src/main/browser/plugin-contribution-handler.ts
  packages/plugin-ext/src/main/browser/plugin-ext-frontend-module.ts
  packages/plugin-ext/src/main/browser/plugin-icon-service.ts
Labels: vscode, ui/ux

#12973 12972+ Localized debug step PAUSED ON
  packages/debug/src/browser/model/debug-thread.tsx
Labels: localization

#12997 Support string argument in `vscode.open`
  packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts
Labels: vscode

#12864 fix: file-saving dialog with dirty editors
  examples/api-tests/src/saveable.spec.js
  packages/core/src/browser/saveable.ts
Labels: file dialog

#12932 [perf] Load localizations lazily
  packages/core/src/node/i18n/localization-contribution.ts
  packages/core/src/node/i18n/localization-provider.ts
  packages/plugin-ext/src/common/plugin-protocol.ts
  packages/plugin-ext/src/hosted/node/hosted-plugin-localization-service.ts
  packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts
Labels: performance, localization

#13031 13030 Localized some warns and infos
  packages/core/src/browser/common-frontend-contribution.ts
Labels: localization

#13028 Update nls metadata for VSCode API 1.82.0
  packages/core/src/browser/core-preferences.ts
  packages/core/src/common/i18n/nls.metadata.json
  packages/filesystem/src/browser/filesystem-preferences.ts
  packages/terminal/src/browser/terminal-preferences.ts
Labels: localization

#13018 Allow tree data providers to return null items
  packages/plugin-ext/src/plugin/tree/tree-views.ts
Labels: vscode
