Repository eclipse-theia/theia, pull requests merged in 2024-11, with the labels that each got.

#14402 Document release process for native dependencies
  doc/Publishing.md
Labels: documentation

#14417 fixed overlapping of outputs when creating a cell at the top
  packages/plugin-ext/src/main/browser/notebooks/renderers/output-webview-internal.ts
Labels: notebook

#14419 Fix active notebook editor staying active as long as the editor is active
  packages/plugin-ext/src/main/browser/editors-and-documents-main.ts
Labels: notebook

#14432 fix(ai): adjust chat input height dynamically
  packages/ai-chat-ui/src/browser/chat-input-widget.tsx
  packages/ai-chat-ui/src/browser/style/index.css
Labels: TheiaAI

#14445 Fix repository URLs in package.json
  packages/plugin-metrics/package.json
  packages/remote/package.json
Labels: repo

#14437 feat: support property ThemeColor id
  CHANGELOG.md
  packages/core/src/common/theme.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
Labels: vscode

#14435 Update Inversify to latest
  dependency-check-baseline.json
  examples/api-samples/src/common/vsx/sample-ovsx-client-factory.ts
  packages/ai-chat/src/common/chat-agents.ts
  packages/bulk-edit/src/browser/bulk-edit-contribution.ts
  packages/collaboration/src/browser/collaboration-file-system-provider.ts
  packages/core/README.md
  packages/core/package.json
  packages/core/src/browser/dialogs.ts
  packages/core/src/browser/shell/view-contribution.ts
  packages/core/src/browser/tree/tree-decorator.ts
  packages/core/src/browser/widgets/widget.ts
  packages/core/src/common/performance/stopwatch.ts
  packages/git/src/browser/blame/blame-decorator.ts
  packages/markers/src/browser/marker-tree.ts
  packages/memory-inspector/src/browser/memory-inspector-frontend-module.ts
  packages/memory-inspector/src/browser/memory-widget/memory-widget.ts
  packages/plugin-ext/src/hosted/common/hosted-plugin.ts
  packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts
  packages/plugin-ext/src/main/node/plugin-deployer-proxy-entry-impl.ts
  packages/process/src/node/process.ts
  packages/task/src/node/task.ts
  packages/terminal/src/browser/terminal-profile-service.ts
  packages/vsx-registry/src/common/vsx-registry-common-module.ts
  yarn.lock
Labels: dependencies

#14446 feat: stub added APIs for LanguageModel in vscode 1.95
  CHANGELOG.md
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
Labels: vscode

#14453 feat: update proposed API MappedEditProviders
  CHANGELOG.md
  packages/plugin/src/theia.proposed.mappedEditsProvider.d.ts
Labels: vscode

#14480 fix selection and improve active text editor behaviour
  packages/plugin-ext/src/main/browser/main-context.ts
  packages/plugin-ext/src/main/browser/notebooks/notebook-documents-and-editors-main.ts
  packages/plugin-ext/src/main/browser/text-editor-main.ts
  packages/plugin-ext/src/plugin/notebook/notebooks.ts
Labels: notebook

#14488 add min height to cell outputs
  packages/plugin-ext/src/main/browser/notebooks/renderers/output-webview-internal.ts
Labels: notebook

#14486 feat(ai): agents can ask for input and continue
  examples/api-samples/package.json
  examples/api-samples/src/browser/api-samples-frontend-module.ts
  examples/api-samples/src/browser/chat/ask-and-continue-chat-agent-contribution.ts
  examples/api-samples/tsconfig.json
  packages/ai-chat-ui/src/browser/ai-chat-ui-frontend-module.ts
  packages/ai-chat-ui/src/browser/chat-response-renderer/question-part-renderer.tsx
  packages/ai-chat-ui/src/browser/chat-tree-view/chat-view-tree-widget.tsx
  packages/ai-chat-ui/src/browser/style/index.css
  packages/ai-chat/src/common/chat-agents.ts
  packages/ai-chat/src/common/chat-model-util.ts
  packages/ai-chat/src/common/chat-model.ts
  packages/ai-chat/src/common/index.ts
  packages/ai-chat/src/common/parse-contents.spec.ts
  packages/ai-chat/src/common/parse-contents.ts
  packages/ai-chat/src/common/response-content-matcher.ts
Labels: TheiaAI

#14498 feat(ai): add hovers for agents and variables
  packages/ai-chat-ui/src/browser/chat-response-renderer/markdown-part-renderer.tsx
  packages/ai-chat-ui/src/browser/chat-tree-view/chat-view-tree-widget.tsx
  packages/ai-chat-ui/src/browser/style/index.css
Labels: TheiaAI

#14531 dev: add eslint rule for annotation checks
  configs/errors.eslintrc.json
  dev-packages/private-eslint-plugin/README.md
  dev-packages/private-eslint-plugin/index.js
  dev-packages/private-eslint-plugin/rules/annotation-check.js
Labels: quality
