Repository eclipse-theia/theia, pull requests merged in 2024-12, with the labels that each got.

#14573 basics to allow for hidden cells
  packages/notebook/src/browser/view-model/notebook-model.ts
  packages/notebook/src/browser/view/notebook-cell-list-view.tsx
  packages/plugin-ext/src/main/browser/notebooks/renderers/cell-output-webview.tsx
Labels: notebook

#14590 [vscode] refactor uri or light/dark uri or ThemeIcon as IconPath type
  packages/plugin/src/theia.d.ts
Labels: vscode

#14563 Improve searchForDevontainerJsonFiles to not block server
  packages/dev-container/src/electron-node/dev-container-file-service.ts
Labels: quality, dev-container

#14533 Cancel pending hover on mouse exit
  packages/core/src/browser/hover-service.ts
Labels: ui/ux

#14617 fixes for invisible cells
  packages/plugin-ext/src/main/browser/notebooks/renderers/cell-output-webview.tsx
Labels: notebook

#14018 Fix editor preference localizations
  packages/editor/src/browser/editor-preferences.ts
Labels: preferences, editor, localization

#14606 Update builtins to 1.95.3
  package.json
Labels: builtins

#14599 Stubs TestRunProfile loadDetailedCoverageForTest
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
Labels: vscode

#14306 Update keytar and drivelist
  examples/api-tests/src/credentials-service.spec.js
  packages/core/package.json
  yarn.lock
Labels: dependencies

#14659 Fix file data streaming for http polling
  packages/filesystem/src/common/remote-file-system-provider.ts
Labels: filesystem, websocket

#14681 Consistently handle OpenAI models not supporting system messages instead of using dedicated O1 chat agent
  packages/ai-chat/src/browser/ai-chat-frontend-module.ts
  packages/ai-chat/src/common/o1-chat-agent.ts
  packages/ai-openai/package.json
  packages/ai-openai/src/browser/openai-frontend-application-contribution.ts
  packages/ai-openai/src/browser/openai-preferences.ts
  packages/ai-openai/src/node/openai-language-model.ts
  yarn.lock
Labels: TheiaAI
