Repository eclipse-theia/theia, pull requests merged in 2025-01, with the labels that each got.

#14594 Add jump to cursor
  packages/debug/src/browser/debug-frontend-application-contribution.ts
  packages/debug/src/browser/debug-session.tsx
  packages/debug/src/browser/editor/debug-editor-service.ts
  packages/debug/src/browser/model/debug-thread.tsx
Labels: vscode, debug

#14734 [vscode] propertly mark chat and language model APIs as stubbed
  packages/plugin/src/theia.d.ts
Labels: vscode

#14365 Include ignored files in `vscode.workspace.findFiles`
  packages/plugin-ext/src/common/plugin-api-rpc.ts
  packages/plugin-ext/src/main/browser/workspace-main.ts
  packages/plugin-ext/src/plugin/workspace.ts
Labels: filesystem, vscode

#14605 Support property Text in DocumentDropOrPasteEditKind
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.proposed.documentPaste.d.ts
Labels: vscode

#14719 stub TerminalCompletionProvider proposed API
  packages/plugin-ext/src/plugin/plugin-context.ts
  packages/plugin-ext/src/plugin/types-impl.ts
  packages/plugin/src/theia.d.ts
  packages/plugin/src/theia.proposed.terminalCompletionProvider.d.ts
Labels: vscode

#14754 Fix `workbench.action.files.newUntitledFile`
  packages/core/src/browser/common-frontend-contribution.ts
  packages/getting-started/src/browser/getting-started-widget.tsx
Labels: vscode, commands

#14720 Provide node-pty package for plugins
  package-lock.json
  packages/plugin-ext/package.json
  packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts
  packages/plugin-ext/src/hosted/node/plugin-require-override.ts
Labels: plug-in system, vscode

#14778 Support `vscode` file system provider scheme
  packages/core/src/browser/frontend-application-module.ts
  packages/core/src/browser/json-schema-store.ts
  packages/debug/src/browser/debug-schema-updater.ts
  packages/filesystem/src/browser/filesystem-frontend-module.ts
  packages/filesystem/src/browser/vscode-file-service-contribution.ts
  packages/preferences/src/browser/preferences-json-schema-contribution.ts
  packages/task/src/browser/task-schema-updater.ts
  packages/workspace/src/browser/workspace-schema-updater.ts
Labels: filesystem, vscode

#14708 Improve bundling for hoisted dependencies
  dev-packages/application-manager/src/generator/webpack-generator.ts
  dev-packages/native-webpack-plugin/src/native-webpack-plugin.ts
Labels: bundle

#14757 Add task related context keys
  packages/task/src/browser/task-context-key-service.ts
  packages/task/src/browser/task-frontend-module.ts
  packages/task/src/browser/task-service.ts
Labels: tasks, vscode

#14699 Load plugin readme from file system
  packages/vsx-registry/src/browser/vsx-extensions-model.ts
Labels: plug-in system

#14756 Support dragging files in browser
  packages/core/src/browser/shell/application-shell.ts
Labels: dnd, browser
